"""
KruschBiz Commercial Document Export Module.
Generates publication-quality, boardroom/executive-ready .docx and .md commercial briefs with
formal corporate memo captions, executive decision summaries, assertion-level verification tables,
and cited contractual appendices.
"""

import io
from datetime import datetime
from typing import Any

import docx
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml import OxmlElement, parse_xml
from docx.oxml.ns import nsdecls, qn
from docx.shared import Inches, Pt, RGBColor


def set_cell_background(cell, hex_color: str):
    """Set background color of a table cell."""
    tcPr = cell._tc.get_or_add_tcPr()
    shd = parse_xml(f'<w:shd {nsdecls("w")} w:fill="{hex_color}"/>')
    tcPr.append(shd)


def set_cell_margins(cell, top=100, bottom=100, left=150, right=150):
    """Set inner padding for table cells in dxa (1 pt = 20 dxa)."""
    tcPr = cell._tc.get_or_add_tcPr()
    tcMar = OxmlElement('w:tcMar')
    for m, val in [('top', top), ('bottom', bottom), ('left', left), ('right', right)]:
        node = OxmlElement(f'w:{m}')
        node.set(qn('w:w'), str(val))
        node.set(qn('w:type'), 'dxa')
        tcMar.append(node)
    tcPr.append(tcMar)


def generate_brief_docx(
    brief_content: str = "",
    deal_title: str = "",
    deal_code: str | None = None,
    counterparty: str | None = None,
    deal_type: str | None = None,
    claims_audit: list[dict[str, Any]] | None = None,
    retrieved_clauses: list[dict[str, Any]] | None = None,
    disclaimer: str | None = None,
    analysis_text: str | None = None,
    claims_records: list[dict[str, Any]] | None = None,
) -> bytes:
    """
    Format a generated executive deal brief into a styled Microsoft Word (.docx) document.
    """
    brief_content = brief_content or analysis_text or ""
    claims_audit = claims_audit or claims_records or []

    doc = docx.Document()

    # 1. Page Setup - 1-inch margins
    for section in doc.sections:
        section.top_margin = Inches(1.0)
        section.bottom_margin = Inches(1.0)
        section.left_margin = Inches(1.0)
        section.right_margin = Inches(1.0)
        section.header.is_linked_to_previous = False
        section.footer.is_linked_to_previous = False

        # Header
        header_p = section.header.paragraphs[0]
        header_p.alignment = WD_ALIGN_PARAGRAPH.RIGHT
        h_run = header_p.add_run(f"CONFIDENTIAL CORPORATE WORK PRODUCT | {deal_code or 'EXECUTIVE PREVIEW'}")
        h_run.font.name = "Arial"
        h_run.font.size = Pt(8.5)
        h_run.font.color.rgb = RGBColor(120, 120, 120)

        # Footer
        footer_p = section.footer.paragraphs[0]
        footer_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        f_run = footer_p.add_run("Generated by KruschBiz Sovereign Corporate Intelligence Engine — Subject to Independent Review")
        f_run.font.name = "Arial"
        f_run.font.size = Pt(8.0)
        f_run.font.color.rgb = RGBColor(140, 140, 140)

    # 2. Document Title / Caption
    title_p = doc.add_paragraph()
    title_p.paragraph_format.space_before = Pt(0)
    title_p.paragraph_format.space_after = Pt(4)
    t_run = title_p.add_run("EXECUTIVE COMMERCIAL MEMORANDUM & CONTRACT ANALYSIS")
    t_run.font.name = "Arial"
    t_run.font.size = Pt(17)
    t_run.font.bold = True
    t_run.font.color.rgb = RGBColor(20, 35, 60)

    # Caption Table
    caption_table = doc.add_table(rows=5, cols=2)
    caption_table.alignment = WD_TABLE_ALIGNMENT.CENTER
    caption_table.autofit = False

    caption_data = [
        ("TRANSACTION / TITLE:", deal_title),
        ("DEAL CODE:", deal_code or "N/A"),
        ("COUNTERPARTY:", counterparty or "Confidential"),
        ("TRANSACTION TYPE:", deal_type or "Commercial Agreement"),
        ("DATE PREPARED:", datetime.now().strftime("%B %d, %Y"))
    ]

    for idx, (label, val) in enumerate(caption_data):
        row = caption_table.rows[idx]
        c0, c1 = row.cells[0], row.cells[1]
        c0.width = Inches(2.2)
        c1.width = Inches(4.3)
        set_cell_background(c0, "F1F5F9")
        set_cell_background(c1, "FFFFFF")
        set_cell_margins(c0, top=60, bottom=60, left=100, right=100)
        set_cell_margins(c1, top=60, bottom=60, left=100, right=100)

        p0 = c0.paragraphs[0]
        p0.paragraph_format.space_after = Pt(0)
        r0 = p0.add_run(label)
        r0.font.name = "Arial"
        r0.font.bold = True
        r0.font.size = Pt(9.0)
        r0.font.color.rgb = RGBColor(50, 65, 85)

        p1 = c1.paragraphs[0]
        p1.paragraph_format.space_after = Pt(0)
        r1 = p1.add_run(val)
        r1.font.name = "Arial"
        r1.font.size = Pt(9.5)
        r1.font.color.rgb = RGBColor(20, 20, 20)

    # Horizontal Divider Line
    div_p = doc.add_paragraph()
    div_p.paragraph_format.space_before = Pt(8)
    div_p.paragraph_format.space_after = Pt(14)
    pBdr = parse_xml(f'<w:pBdr {nsdecls("w")}><w:bottom w:val="single" w:sz="12" w:space="1" w:color="0284C7"/></w:pBdr>')
    div_p._p.get_or_add_pPr().append(pBdr)

    # 3. Main Body Analysis Parsing
    lines = brief_content.split("\n")
    skip_disclaimer_block = False

    for line in lines:
        stripped = line.strip()
        if not stripped:
            continue

        if "Corporate Governance Notice" in stripped or "DISCLAIMER:" in stripped:
            skip_disclaimer_block = True
            continue

        if skip_disclaimer_block:
            continue

        if stripped.startswith("### "):
            hp = doc.add_paragraph()
            hp.paragraph_format.space_before = Pt(10)
            hp.paragraph_format.space_after = Pt(3)
            hr = hp.add_run(stripped.replace("### ", ""))
            hr.font.name = "Arial"
            hr.font.bold = True
            hr.font.size = Pt(11.5)
            hr.font.color.rgb = RGBColor(30, 41, 59)
        elif stripped.startswith("## "):
            hp = doc.add_paragraph()
            hp.paragraph_format.space_before = Pt(14)
            hp.paragraph_format.space_after = Pt(4)
            hr = hp.add_run(stripped.replace("## ", ""))
            hr.font.name = "Arial"
            hr.font.bold = True
            hr.font.size = Pt(13)
            hr.font.color.rgb = RGBColor(14, 116, 144)
        elif stripped.startswith("# "):
            hp = doc.add_paragraph()
            hp.paragraph_format.space_before = Pt(18)
            hp.paragraph_format.space_after = Pt(6)
            hr = hp.add_run(stripped.replace("# ", ""))
            hr.font.name = "Arial"
            hr.font.bold = True
            hr.font.size = Pt(14.5)
            hr.font.color.rgb = RGBColor(20, 35, 60)
        elif stripped.startswith("> "):
            qp = doc.add_paragraph()
            qp.paragraph_format.left_indent = Inches(0.4)
            qp.paragraph_format.space_before = Pt(3)
            qp.paragraph_format.space_after = Pt(3)
            clean_q = stripped.replace("> ", "").replace("**", "")
            qr = qp.add_run(clean_q)
            qr.font.name = "Arial"
            qr.font.italic = True
            qr.font.size = Pt(9.5)
            qr.font.color.rgb = RGBColor(70, 70, 70)
        else:
            bp = doc.add_paragraph()
            bp.paragraph_format.space_before = Pt(2)
            bp.paragraph_format.space_after = Pt(5)
            bp.paragraph_format.line_spacing = 1.15
            clean_b = stripped.replace("**", "")
            br = bp.add_run(clean_b)
            br.font.name = "Calibri"
            br.font.size = Pt(10.5)
            br.font.color.rgb = RGBColor(30, 30, 30)

    # 4. Appendix A: Assertion-Level Grounding Audit Table
    if claims_audit:
        doc.add_page_break()
        app_title = doc.add_paragraph()
        app_title.paragraph_format.space_before = Pt(10)
        app_title.paragraph_format.space_after = Pt(4)
        ar = app_title.add_run("APPENDIX A: ASSERTION-LEVEL COMMERCIAL GROUNDING AUDIT")
        ar.font.name = "Arial"
        ar.font.bold = True
        ar.font.size = Pt(14)
        ar.font.color.rgb = RGBColor(20, 35, 60)

        intro = doc.add_paragraph()
        intro.paragraph_format.space_after = Pt(10)
        ir = intro.add_run(
            "Every claim and citation in this brief was scanned against verified governing agreements. "
            "Verified propositions correlate to verbatim contract language. Flagged items require manual confirmation."
        )
        ir.font.name = "Arial"
        ir.font.size = Pt(9.0)
        ir.font.color.rgb = RGBColor(100, 100, 100)

        # Audit Table
        table = doc.add_table(rows=1, cols=4)
        table.alignment = WD_TABLE_ALIGNMENT.CENTER
        table.autofit = False

        headers = ["Claim #", "Asserted Commercial Term", "Cited Authority", "Grounding Status"]
        widths = [Inches(0.8), Inches(3.0), Inches(1.4), Inches(1.3)]
        hdr_row = table.rows[0]

        for idx, (h, w) in enumerate(zip(headers, widths)):
            cell = hdr_row.cells[idx]
            cell.width = w
            set_cell_background(cell, "0F172A")
            set_cell_margins(cell, top=80, bottom=80, left=100, right=100)
            p = cell.paragraphs[0]
            p.alignment = WD_ALIGN_PARAGRAPH.LEFT
            r = p.add_run(h)
            r.font.name = "Arial"
            r.font.bold = True
            r.font.size = Pt(8.5)
            r.font.color.rgb = RGBColor(255, 255, 255)

        for c_idx, claim in enumerate(claims_audit):
            row = table.add_row()
            status = claim.get("status", "unverified")
            status_colors = {
                "verified_grounded": "E8F5E9",
                "divergent_term": "FFF3E0",
                "invented_clause": "FFEBEE",
                "superseded_term": "EDE7F6"
            }
            bg_color = status_colors.get(status, "FFFFFF")

            c_num = row.cells[0]
            c_num.width = widths[0]
            set_cell_background(c_num, bg_color)
            set_cell_margins(c_num, 50, 50, 80, 80)
            p0 = c_num.paragraphs[0]
            r0 = p0.add_run(claim.get("claim_id", f"#{c_idx+1}"))
            r0.font.name = "Arial"
            r0.font.size = Pt(8.0)

            c_sent = row.cells[1]
            c_sent.width = widths[1]
            set_cell_background(c_sent, bg_color)
            set_cell_margins(c_sent, 50, 50, 80, 80)
            p1 = c_sent.paragraphs[0]
            sent_text = claim.get("sentence", "")
            r1 = p1.add_run(sent_text[:140] + ("..." if len(sent_text) > 140 else ""))
            r1.font.name = "Arial"
            r1.font.size = Pt(8.0)

            c_auth = row.cells[2]
            c_auth.width = widths[2]
            set_cell_background(c_auth, bg_color)
            set_cell_margins(c_auth, 50, 50, 80, 80)
            p2 = c_auth.paragraphs[0]
            r2 = p2.add_run(claim.get("cited_authority", "N/A"))
            r2.font.name = "Arial"
            r2.font.bold = True
            r2.font.size = Pt(8.0)

            c_stat = row.cells[3]
            c_stat.width = widths[3]
            set_cell_background(c_stat, bg_color)
            set_cell_margins(c_stat, 50, 50, 80, 80)
            p3 = c_stat.paragraphs[0]
            status_labels = {
                "verified_grounded": "VERIFIED",
                "divergent_term": "DIVERGENT",
                "invented_clause": "INVENTED",
                "superseded_term": "SUPERSEDED"
            }
            r3 = p3.add_run(status_labels.get(status, status.upper()))
            r3.font.name = "Arial"
            r3.font.bold = True
            r3.font.size = Pt(8.0)

    # 5. Appendix B: Table of Contract Authorities Retrieved
    if retrieved_clauses:
        doc.add_page_break()
        app_b = doc.add_paragraph()
        app_b.paragraph_format.space_before = Pt(10)
        app_b.paragraph_format.space_after = Pt(4)
        br = app_b.add_run("APPENDIX B: TABLE OF CONTRACTUAL AUTHORITIES RETRIEVED")
        br.font.name = "Arial"
        br.font.bold = True
        br.font.size = Pt(14)
        br.font.color.rgb = RGBColor(20, 35, 60)

        for cl in retrieved_clauses:
            cp = doc.add_paragraph()
            cp.paragraph_format.space_before = Pt(6)
            cp.paragraph_format.space_after = Pt(2)
            sec_name = cl.get("section") or "Section"
            title_name = cl.get("title") or sec_name
            org_name = cl.get("organization") or "Enterprise"
            auth_cls = (cl.get("authority_class") or "Agreement").replace("_", " ").upper()

            c_head = cp.add_run(f"[{auth_cls}] {org_name} — {title_name} ({sec_name})")
            c_head.font.name = "Arial"
            c_head.font.bold = True
            c_head.font.size = Pt(10.0)
            c_head.font.color.rgb = RGBColor(14, 116, 144)

            bp = doc.add_paragraph()
            bp.paragraph_format.left_indent = Inches(0.2)
            bp.paragraph_format.space_after = Pt(4)
            b_run = bp.add_run(cl.get("content", ""))
            b_run.font.name = "Calibri"
            b_run.font.size = Pt(9.0)
            b_run.font.color.rgb = RGBColor(60, 60, 60)

    # 6. Corporate Governance Disclaimer Box
    disc_p = doc.add_paragraph()
    disc_p.paragraph_format.space_before = Pt(20)
    disc_p.paragraph_format.space_after = Pt(4)
    disc_run = disc_p.add_run("CORPORATE GOVERNANCE DISCLAIMER")
    disc_run.font.name = "Arial"
    disc_run.font.bold = True
    disc_run.font.size = Pt(9.0)
    disc_run.font.color.rgb = RGBColor(180, 83, 9)

    box = doc.add_paragraph()
    box.paragraph_format.space_before = Pt(2)
    box.paragraph_format.left_indent = Inches(0.2)
    box_pBdr = parse_xml(f'<w:pBdr {nsdecls("w")}><w:left w:val="single" w:sz="18" w:space="6" w:color="F59E0B"/></w:pBdr>')
    box._p.get_or_add_pPr().append(box_pBdr)

    raw_disc = disclaimer or (
        "This commercial memorandum was generated by KruschBiz, an offline sovereign AI corporate intelligence engine. "
        "It is provided for preliminary risk assessment and deal analysis only. Independent attorney verification is required."
    )
    b_run = box.add_run(raw_disc)
    b_run.font.name = "Arial"
    b_run.font.italic = True
    b_run.font.size = Pt(8.5)
    b_run.font.color.rgb = RGBColor(80, 80, 80)

    # Save to memory buffer
    buffer = io.BytesIO()
    doc.save(buffer)
    buffer.seek(0)
    return buffer.getvalue()


def generate_brief_markdown(
    brief_content: str = "",
    deal_title: str = "",
    deal_code: str | None = None,
    counterparty: str | None = None,
    deal_type: str | None = None,
    claims_audit: list[dict[str, Any]] | None = None,
    retrieved_clauses: list[dict[str, Any]] | None = None,
    disclaimer: str | None = None,
    analysis_text: str | None = None,
    claims_records: list[dict[str, Any]] | None = None,
) -> str:
    """Format executive brief into structured markdown with audit tables."""
    brief_content = brief_content or analysis_text or ""
    claims_audit = claims_audit or claims_records or []
    lines = [
        "# EXECUTIVE COMMERCIAL MEMORANDUM & CONTRACT ANALYSIS",
        f"**Transaction / Title**: {deal_title}  ",
        f"**Deal Code**: {deal_code or 'N/A'}  ",
        f"**Counterparty**: {counterparty or 'Confidential'}  ",
        f"**Transaction Type**: {deal_type or 'Commercial Agreement'}  ",
        f"**Date Prepared**: {datetime.now().strftime('%B %d, %Y')}  ",
        "\n---\n",
        brief_content,
        "\n---\n"
    ]

    if claims_audit:
        lines.append("## APPENDIX A: ASSERTION-LEVEL COMMERCIAL GROUNDING AUDIT\n")
        lines.append("| Claim # | Asserted Commercial Term | Cited Authority | Grounding Status | Failure Mode |")
        lines.append("| --- | --- | --- | --- | --- |")
        for claim in claims_audit:
            cid = claim.get("claim_id", "")
            sent = claim.get("sentence", "").replace("|", "\\|")
            auth = claim.get("cited_authority", "").replace("|", "\\|")
            stat = claim.get("status", "")
            fail = claim.get("failure_mode") or "None"
            lines.append(f"| {cid} | {sent[:80]}... | {auth} | **{stat.upper()}** | {fail} |")
        lines.append("\n---\n")

    if retrieved_clauses:
        lines.append("## APPENDIX B: TABLE OF CONTRACTUAL AUTHORITIES RETRIEVED\n")
        for cl in retrieved_clauses:
            sec = cl.get("section", "Section")
            title = cl.get("title", sec)
            org = cl.get("organization", "Enterprise")
            auth = (cl.get("authority_class") or "Agreement").replace("_", " ").upper()
            content = cl.get("content", "")
            lines.append(f"### [{auth}] {org} — {title} ({sec})\n")
            lines.append(f"> {content}\n")
        lines.append("\n---\n")

    lines.append("### Corporate Governance Notice\n")
    lines.append(f"> {disclaimer or 'Subject to independent executive and legal verification.'}\n")

    return "\n".join(lines)


# Aliases for backward compatibility and canonical export naming
export_executive_memo_docx = generate_brief_docx
export_executive_memo_markdown = generate_brief_markdown
