"""
src/backend/rag.py
==================
Commercial RAG, hybrid retrieval, authority hierarchy weighting,
and assertion-level proposition grounding engine.
Features:
  - Hybrid dense ANN (pgvector / cosine) + full-text lexical search with Reciprocal Rank Fusion
  - Hierarchical authority weighting and explainable ranking breakdown
  - Assertion-level proposition grounding scanner with span overlap + structured slot match
  - Multi-failure taxonomy: INVENTED_CLAUSE, DIVERGENT_TERM, SUPERSEDED_TERM, VERIFIED
  - Refusal guardrails: CANNOT_DRAFT_WITHOUT_AUTHORITIES, REFUSAL_ALL_AUTHORITIES_SUPERSEDED
"""

from __future__ import annotations

import hashlib
import json
import logging
import math
import re
import threading
from collections import OrderedDict
from typing import Any

import httpx
from sqlalchemy import text
from sqlalchemy.orm import Session

from .config import settings
from .db import CommercialClauseVector, CommercialGroundingReport, DealEvidence
from .taxonomy import CANONICAL_TOPICS, extract_structured_slots, get_slot_val

logger = logging.getLogger("kruschbiz.rag")

COMMERCIAL_DISCLAIMER = (
    "DISCLAIMER: This analysis was generated by KruschBiz, an offline, air-gapped corporate intelligence engine. "
    "This document is provided strictly for executive review, commercial risk spotting, and deal diligence. "
    "It does NOT constitute formal legal opinion or replace certified legal counsel. "
    "Admitted counsel and corporate officers must independently verify all contractual terms, indemnities, "
    "and regulatory commitments prior to execution or formal reliance."
)

AUTHORITY_WEIGHTS = {
    "governing_agreement": 1.25,
    "amendment_addendum": 1.20,
    "statement_of_work": 1.10,
    "corporate_policy": 1.00,
    "regulatory_framework": 0.95,
    "commercial_code": 0.90,
    "secondary_guideline": 0.80,
}

COMMERCIAL_ISSUE_RULES: list[dict[str, Any]] = [
    {
        "issue": "Payment Terms & Invoicing Due Date",
        "domain": "Procurement & Invoicing",
        "governing_authorities": "Section 4.1",
        "keywords": [
            r"\bpayment\s+deadline\b", r"\binvoice\s+date\b", r"\bnet\s*(?:30|45)\b",
            r"\bundisputed\s+(?:amounts?|charges?|invoices?)\b", r"\bach\b", r"\bwire\s+transfer\b",
            r"\bmethod\s+of\s+payment\b", r"\bdispute\s+notice\b", r"\bstandard\s+payment\b"
        ],
        "commercial_terms": "Section 4.1 Payment Terms invoicing undisputed amount Net 30 days ACH wire transfer good faith dispute notice"
    },
    {
        "issue": "Late Payment Penalties & Suspension of Service",
        "domain": "Procurement & Invoicing",
        "governing_authorities": "Section 4.2",
        "keywords": [
            r"\boverdue\b", r"\blate\s+(?:fee|payment|interest)\b", r"\b1\.5%?\b",
            r"\bsuspend\b", r"\bsuspending\s+services?\b", r"\bdelinquent\b",
            r"\bten\s*\(10\)\s*business\s+days\b", r"\bhow\s+many\s+business\s+days\s+notice\b"
        ],
        "commercial_terms": "Section 4.2 Late Payment Penalties late interest 1.5 percent per month suspend cloud service ten 10 business days prior written notice"
    },
    {
        "issue": "Mutual Limitation of Liability Cap",
        "domain": "Risk & Indemnification",
        "governing_authorities": "Section 10.1",
        "keywords": [
            r"\blimitation\s+of\s+liability\b", r"\bliability\s+cap\b", r"\bconsequential\s+damages\b",
            r"\btwelve\s*\(12\)\s*months\b", r"\b12\s+months\b", r"\bfees\s+paid\b",
            r"\baggregate\s+liability\b", r"\bcap\s+on\s+damages\b"
        ],
        "commercial_terms": "Section 10.1 Limitation of Liability aggregate liability twelve 12 months preceding incident fees paid lost profits indirect damages"
    },
    {
        "issue": "Uncapped Liability Carve-Outs and Exclusions",
        "domain": "Risk & Indemnification",
        "governing_authorities": "Section 10.2",
        "keywords": [
            r"\bcarve[\s-]?outs?\b", r"\buncapped\s+liability\b", r"\bgross\s+negligence\b",
            r"\bwillful\s+misconduct\b", r"\bbreach\s+of\s+confidentiality\b", r"\bexclusions?\s+from\s+cap\b",
            r"\bexceptions?\s+to\s+liability\b", r"\bnot\s+apply\s+to\b"
        ],
        "commercial_terms": "Section 10.2 Carve-outs and Exclusions gross negligence willful misconduct intentional fraud breach confidentiality Section 8"
    },
    {
        "issue": "Mutual Indemnification for Third-Party IP Claims",
        "domain": "Risk & Indemnification",
        "governing_authorities": "Section 11.1",
        "keywords": [
            r"\bindemnif(?:y|ication|ied)\b", r"\bhold\s+harmless\b", r"\bdefend\b",
            r"\bpatent\s+infringement\b", r"\bcopyright\s+infringement\b", r"\bthird[\s-]?party\s+claims?\b",
            r"\bsole\s+control\s+of\s+defense\b", r"\bprompt\s+written\s+notice\b"
        ],
        "commercial_terms": "Section 11.1 Mutual Indemnification patent copyright trademark infringement prompt written notice sole control defense"
    },
    {
        "issue": "CloudScale SLA Monthly Uptime Percentage",
        "domain": "Service Levels & Operations",
        "governing_authorities": "Exhibit B (SLA) Section 2.1",
        "keywords": [
            r"\buptime\s+percentage\b", r"\b99\.9%?\b", r"\bavailability\s+commitment\b",
            r"\boperational\s+due\s+diligence\b", r"\bhealth\s+probes\b", r"\bhttp\s*200\b"
        ],
        "commercial_terms": "Exhibit B Section 2.1 Availability Commitment Monthly Uptime Percentage 99.9% availability external health probes"
    },
    {
        "issue": "CloudScale SLA Maintenance Window Exclusions",
        "domain": "Service Levels & Operations",
        "governing_authorities": "Exhibit B (SLA) Section 2.2",
        "keywords": [
            r"\bscheduled\s+maintenance\b", r"\bmaintenance\s+window\b", r"\bsundays?\b",
            r"\b01:00\b", r"\b05:00\b", r"\b48\s+hours\b", r"\bforty-eight\s+\(48\)\s+hours\b"
        ],
        "commercial_terms": "Exhibit B Section 2.2 Maintenance Exclusions scheduled maintenance weekly maintenance window Sundays 01:00-05:00 UTC forty-eight 48 hours notice"
    },
    {
        "issue": "CloudScale SLA Service Credit Remedies",
        "domain": "Service Levels & Operations",
        "governing_authorities": "Exhibit B (SLA) Section 2.3",
        "keywords": [
            r"\bservice\s+credits?\b", r"\bcredit\s+percentage\b", r"\bunscheduled\s+outage\b",
            r"\b97\.5%?\b", r"\b93\.8%?\b", r"\bsole\s+and\s+exclusive\s+remedy\b",
            r"\b10%\s+credit\b", r"\b25%\s+credit\b", r"\b50%\s+credit\b"
        ],
        "commercial_terms": "Exhibit B Section 2.3 Service Credits credit percentage 95.0% to 98.99% 25% credit less than 95.0% 50% credit exclusive remedy"
    },
    {
        "issue": "Data Protection Addendum & SOC2 Type II Certification",
        "domain": "Security & Data Privacy",
        "governing_authorities": "Exhibit C (DPA) Section 3.1",
        "keywords": [
            r"\bsoc\s*2\b", r"\btype\s*ii\b", r"\baicpa\b", r"\bsecurity\s+standards?\b",
            r"\bannual\s+independent\b", r"\bauditor['’]?s?\s+report\b", r"\bhow\s+often\b"
        ],
        "commercial_terms": "Exhibit C Section 3.1 Security Standards AICPA SOC 2 Type II annual independent auditor report"
    },
    {
        "issue": "Data Protection Addendum 24-Hour Breach Notification",
        "domain": "Security & Data Privacy",
        "governing_authorities": "Exhibit C (DPA) Section 3.4",
        "keywords": [
            r"\bsecurity\s+incident\b", r"\bbreach\s+notification\b", r"\b24\s+hours?\b",
            r"\btwenty-four\s*\(24\)\s*hours?\b", r"\bpersonal\s+data\b", r"\bdata\s+breach\b",
            r"\bunauthorized\s+access\b", r"\bdaily\s+status\s+briefings\b"
        ],
        "commercial_terms": "Exhibit C Section 3.4 Security Incident Notification twenty-four 24 hours email telephone daily briefings unauthorized access"
    },
    {
        "issue": "Corporate Delegated Authority Approval Thresholds",
        "domain": "Corporate Governance & Delegated Authority",
        "governing_authorities": "Article IV Section 4.3",
        "keywords": [
            r"\bdelegated\s+authority\b", r"\bsignature\s+authorization\b", r"\bapproval\s+limits?\b",
            r"\bboard\s+of\s+directors\b", r"\bboard\s+approval\b", r"\$1,?000,?000\b",
            r"\bexceeding\s+\$1,?000,?000\b", r"\$250,?000\b", r"\$50,?000\b"
        ],
        "commercial_terms": "Article IV Section 4.3 Delegated Authority Thresholds signature limits Board Directors 1000000 CEO CFO 250000 VP 50000 Director"
    },
    {
        "issue": "Commercial Office Lease NNN Operating Expenses & CAM",
        "domain": "Real Estate & Leasing",
        "governing_authorities": "Lease § 5.2",
        "keywords": [
            r"\boperating\s+expenses\b", r"\bcam\b", r"\bcommon\s+area\s+maintenance\b",
            r"\btriple\s+net\b", r"\bnnn\b", r"\bpro\s+rata\s+share\b", r"\b14\.2%?\b",
            r"\badditional\s+rent\b", r"\bcapital\s+expenditures\b", r"\bmortgage\s+interest\b"
        ],
        "commercial_terms": "Lease Section 5.2 Operating Expenses CAM Common Area Maintenance Pro Rata Share 14.2 percent capital expenditures mortgage interest exclusions"
    },
    {
        "issue": "Commercial Office Lease Annual CAM Audit Rights",
        "domain": "Real Estate & Leasing",
        "governing_authorities": "Lease § 5.4",
        "keywords": [
            r"\bcam\s+audit\b", r"\baudit\s+rights?\b", r"\baudit\s+landlord\b",
            r"\bbooks\s+and\s+records\b", r"\bwithin\s+ninety\s+\(90\)\s+days\b",
            r"\bovercharge\s+exceeding\s+five\s+percent\b", r"\bhow\s+much\s+advance\s+notice\b"
        ],
        "commercial_terms": "Lease Section 5.4 CAM Audit Rights examine audit books 90 days ten 10 business days advance notice overcharge exceeding 5 percent"
    }
]


_QUERY_EXPANSION_CACHE: OrderedDict[str, tuple[str, list[dict[str, str]]]] = OrderedDict()
_QUERY_EXPANSION_LOCK = threading.Lock()
_QUERY_EXPANSION_MAX = 5000


def expand_commercial_query(text_content: str) -> tuple[str, list[dict[str, str]]]:
    """
    Spot commercial issues from natural language inquiries, extracting structured slots
    and synthesizing canonical search terms. Backed by LRU cache.
    """
    if not text_content or not text_content.strip():
        return text_content, []

    cache_key = text_content.strip()
    with _QUERY_EXPANSION_LOCK:
        if cache_key in _QUERY_EXPANSION_CACHE:
            _QUERY_EXPANSION_CACHE.move_to_end(cache_key)
            return _QUERY_EXPANSION_CACHE[cache_key]

    spotted: list[dict[str, str]] = []
    collected_terms: list[str] = []
    text_lower = text_content.lower()

    # 1. Closed taxonomy & structured slot extraction
    topic, slots = extract_structured_slots(text_content)
    if topic in CANONICAL_TOPICS:
        collected_terms.append(topic.replace("_", " ").lower())
    for k, v in slots.items():
        val = get_slot_val(v)
        collected_terms.append(f"{k} {val}")

    # 2. Bootstrapping teacher rules
    for rule in COMMERCIAL_ISSUE_RULES:
        matched = False
        for kw in rule["keywords"]:
            if re.search(kw, text_lower):
                matched = True
                break
        if matched:
            spotted.append({
                "issue": rule["issue"],
                "domain": rule["domain"],
                "governing_authorities": rule["governing_authorities"]
            })
            collected_terms.append(rule["commercial_terms"])

    if collected_terms:
        expanded_query = f"{text_content} {' '.join(collected_terms)}"
    else:
        expanded_query = text_content

    result = (expanded_query, spotted)
    with _QUERY_EXPANSION_LOCK:
        _QUERY_EXPANSION_CACHE[cache_key] = result
        _QUERY_EXPANSION_CACHE.move_to_end(cache_key)
        if len(_QUERY_EXPANSION_CACHE) > _QUERY_EXPANSION_MAX:
            _QUERY_EXPANSION_CACHE.popitem(last=False)

    return result


class RetrievalError(RuntimeError):
    """Raised when contract or policy search fails."""


class EmbeddingCache:
    """Thread-safe LRU cache for embeddings keyed by model and sha256 text hash."""
    def __init__(self, maxsize: int = 10000):
        self.maxsize = maxsize
        self._cache: OrderedDict[str, list[float]] = OrderedDict()
        self._lock = threading.Lock()
        self.hits = 0
        self.misses = 0

    def _key(self, model: str, text: str) -> str:
        text_hash = hashlib.sha256(text.encode("utf-8")).hexdigest()
        return f"{model}:{text_hash}"

    def get(self, model: str, text: str) -> list[float] | None:
        key = self._key(model, text)
        with self._lock:
            if key in self._cache:
                self.hits += 1
                self._cache.move_to_end(key)
                return self._cache[key]
            self.misses += 1
            return None

    def set(self, model: str, text: str, vector: list[float]) -> None:
        key = self._key(model, text)
        with self._lock:
            self._cache[key] = vector
            self._cache.move_to_end(key)
            if len(self._cache) > self.maxsize:
                self._cache.popitem(last=False)

    def stats(self) -> dict[str, Any]:
        with self._lock:
            total = self.hits + self.misses
            hit_ratio = (self.hits / total) if total > 0 else 0.0
            return {
                "size": len(self._cache),
                "maxsize": self.maxsize,
                "hits": self.hits,
                "misses": self.misses,
                "hit_ratio": round(hit_ratio, 4)
            }

    def clear(self) -> None:
        with self._lock:
            self._cache.clear()
            self.hits = 0
            self.misses = 0


embedding_cache = EmbeddingCache(maxsize=10000)


def get_embeddings_batch(queries: list[str]) -> list[list[float]]:
    """Generate vector embeddings in batch via Ollama API with LRU cache."""
    if not queries:
        return []
    clean_queries = [q.strip() if q and q.strip() else " " for q in queries]

    results: list[list[float] | None] = [None] * len(clean_queries)
    miss_indices: list[int] = []
    miss_texts: list[str] = []

    for idx, q in enumerate(clean_queries):
        cached = embedding_cache.get(settings.OLLAMA_EMBED_MODEL, q)
        if cached is not None:
            results[idx] = cached
        else:
            miss_indices.append(idx)
            miss_texts.append(q)

    if not miss_texts:
        return [r for r in results if r is not None]

    payload = {
        "model": settings.OLLAMA_EMBED_MODEL,
        "input": miss_texts
    }
    fetched: list[list[float]] = []
    try:
        timeout = max(settings.EMBED_TIMEOUT, settings.EMBED_TIMEOUT * (len(miss_texts) / 8.0))
        with httpx.Client(timeout=timeout) as client:
            resp = client.post(f"{settings.OLLAMA_EMBED_HOST}/api/embed", json=payload)
            if resp.status_code == 404:
                # Fallback to single queries
                for mt in miss_texts:
                    s_resp = client.post(
                        f"{settings.OLLAMA_EMBED_HOST}/api/embeddings",
                        json={"model": settings.OLLAMA_EMBED_MODEL, "prompt": mt}
                    )
                    s_resp.raise_for_status()
                    fetched.append(s_resp.json().get("embedding", []))
            else:
                resp.raise_for_status()
                data = resp.json()
                fetched = data.get("embeddings", [])

        for idx, vec in zip(miss_indices, fetched):
            embedding_cache.set(settings.OLLAMA_EMBED_MODEL, clean_queries[idx], vec)
            results[idx] = vec

    except Exception as e:
        logger.warning(f"Ollama batch embedding generation unavailable ({e}).")
        raise RetrievalError(f"CANNOT_DRAFT_EMBEDDINGS_UNAVAILABLE: Embedding generation offline ({e}). Drafting on constant vectors is strictly prohibited.")

    return [r for r in results if r is not None]


_real_get_embeddings_batch = get_embeddings_batch


def get_embedding(query: str) -> list[float]:
    """Generate vector embedding for single query."""
    res = get_embeddings_batch([query])
    if not res:
        raise RetrievalError("CANNOT_DRAFT_EMBEDDINGS_UNAVAILABLE: No embedding returned from service.")
    return res[0]


def score_retrieval_candidate(
    cand: dict[str, Any],
    query_vector: list[float] | None,
    query_words: set[str],
    quoted_phrases: list[str],
    section_patterns: list[str],
    spotted_auths: list[str],
    spotted_tags: set[str]
) -> dict[str, Any]:
    """
    Unified Python scoring function applied identically to candidates fetched via SQLite or Postgres.
    Evaluates:
      - Cosine vector similarity (vec_score)
      - Substantive lexical token overlap (lex_score)
      - Commercial taxonomy tag alignment (tag_score)
      - Authority hierarchy weight (auth_mult)
      - Section citation & quote boosts (section_boost)
      - Heavy penalty on superseded/terminated instruments (superseded_penalty = 0.05)
    """
    # 1. Vector score (cosine similarity)
    vec_score = 0.0
    if query_vector is not None and cand.get("embedding"):
        try:
            c_vec = cand["embedding"] if isinstance(cand["embedding"], list) else json.loads(cand["embedding"])
            dot = sum(a * b for a, b in zip(query_vector, c_vec))
            norm_a = math.sqrt(sum(a * a for a in query_vector))
            norm_b = math.sqrt(sum(b * b for b in c_vec))
            if norm_a > 0 and norm_b > 0:
                vec_score = max(0.0, min(1.0, dot / (norm_a * norm_b)))
        except Exception:
            vec_score = 0.0

    # 2. Lexical score (token overlap)
    text_to_search = f"{cand.get('title') or ''} {cand.get('section') or ''} {cand.get('content') or ''}".lower()
    clause_words = set(re.findall(r'\w+', text_to_search))
    overlap = len(query_words.intersection(clause_words))
    lex_score = min(1.0, overlap / (len(query_words) + 1e-5)) if query_words else 0.0

    # 3. Tag score
    cand_tags = set(t.lower() for t in (cand.get("tags") or []))
    if cand.get("topic"):
        cand_tags.add(cand["topic"].lower())
    tag_overlap = len(spotted_tags.intersection(cand_tags))
    tag_score = min(1.0, tag_overlap / (max(1, len(spotted_tags)))) if spotted_tags else 0.0

    # 4. Base hybrid score
    if query_vector is not None and vec_score > 0:
        base_score = 0.45 * vec_score + 0.35 * lex_score + 0.20 * tag_score
    else:
        base_score = 0.70 * lex_score + 0.30 * tag_score

    # 5. Authority class multiplier
    auth_class = cand.get("authority_class", "governing_agreement")
    auth_mult = AUTHORITY_WEIGHTS.get(auth_class, 1.0)

    # 6. Specific section citation & quoted phrase boost
    section_str = (cand.get("section") or "").lower()
    title_str = (cand.get("title") or "").lower()
    content_lower = (cand.get("content") or "").lower()

    boost = 1.0
    for pat in section_patterns:
        clean_pat = re.sub(r'[^\w\.]', '', pat.lower())
        if clean_pat and (clean_pat in section_str or clean_pat in title_str):
            boost *= 1.4

    for phrase in quoted_phrases:
        if phrase.lower() in content_lower:
            boost *= 1.25

    for sp_auth in spotted_auths:
        if sp_auth in section_str or sp_auth in title_str:
            boost *= 1.6
            break

    # 7. Superseded penalty (heavy penalty so Gate 3 priority inversions are structurally impossible)
    is_superseded = bool(cand.get("superseded") or cand.get("terminated"))
    superseded_penalty = 0.05 if is_superseded else 1.0

    final_score = base_score * auth_mult * boost * superseded_penalty

    cand["score"] = final_score
    cand["vector_score"] = vec_score
    cand["lexical_score"] = lex_score
    cand["tag_score"] = tag_score
    cand["explanation"] = {
        "vec_score": round(vec_score, 4),
        "lex_score": round(lex_score, 4),
        "tag_score": round(tag_score, 4),
        "base_score": round(base_score, 4),
        "authority_class": auth_class,
        "authority_weight": round(auth_mult, 2),
        "section_boost": round(boost, 2),
        "superseded_penalty": round(superseded_penalty, 2),
        "final_score": round(final_score, 4),
        "controlling_status": "superseded" if is_superseded else "active",
        "structured_slots": cand.get("structured_slots") or {}
    }
    return cand


def retrieve_clauses(
    db: Session,
    query: str,
    limit: int = 5,
    offset: int = 0,
    organization: str | None = None,
    agreement_type: str | None = None,
    domain: str | None = None,
    deal_id: int | None = None,
    exclude_superseded: bool = True,
    topic: str | None = None,
    tag: str | None = None,
    tenant_id: str = "org_default",
    expand_query: bool = False,
) -> list[dict[str, Any]]:
    """
    Hybrid semantic (ANN) + lexical (FTS) retrieval across commercial contracts and policies.
    Fetches candidate set via SQL, then applies single, unified Python ranking across all dialects.
    """
    if not query or not query.strip():
        return []

    if expand_query:
        expanded_query, spotted_issues = expand_commercial_query(query)
    else:
        expanded_query, spotted_issues = query, []

    is_sqlite = db.bind.dialect.name == "sqlite"

    query_vector = None
    try:
        query_vector = get_embedding(expanded_query)
    except RetrievalError as e:
        logger.info(f"Vector search offline ({e}), falling back to lexical + tag candidate retrieval.")
    except Exception as e:
        logger.warning(f"Vector embedding generation failed ({e}), continuing with lexical candidates.")

    quoted_phrases = re.findall(r'"([^"]+)"', query)
    section_patterns = re.findall(
        r'(?:section|clause|art(?:icle)?|lease\s*§|§)\s*([\w\.\-]+(?:\([a-zA-Z\d]+\))*)',
        expanded_query,
        re.IGNORECASE
    )
    spotted_auths = [issue["governing_authorities"].lower() for issue in spotted_issues if issue.get("governing_authorities")]
    spotted_tags = set(w.lower() for issue in spotted_issues for w in issue.get("keywords", []))
    for t_kw in re.findall(r'\b[a-z]{3,}\b', expanded_query.lower()):
        spotted_tags.add(t_kw)

    raw_candidates: dict[int, dict[str, Any]] = {}

    # 1. Fetch Candidates (Postgres Path: pgvector ANN + Full Text Search)
    if not is_sqlite and query_vector is not None:
        try:
            vec_str = json.dumps(query_vector)
            sql = """
                WITH vector_ranks AS (
                    SELECT id
                    FROM commercial_clauses_vectors
                    WHERE embedding IS NOT NULL
                      AND tenant_id = :tenant_id
                      AND (:organization IS NULL OR organization ILIKE :organization)
                      AND (:agreement_type IS NULL OR agreement_type ILIKE :agreement_type)
                      AND (:domain IS NULL OR domain ILIKE :domain)
                      AND (:topic IS NULL OR topic ILIKE :topic)
                      AND (:tag IS NULL OR tags ILIKE :tag)
                      AND (:exclude_superseded = FALSE OR (superseded = FALSE AND terminated = FALSE))
                    ORDER BY embedding <=> :query_vector::vector
                    LIMIT 40
                ),
                fts_ranks AS (
                    SELECT id
                    FROM commercial_clauses_vectors
                    WHERE tenant_id = :tenant_id
                      AND to_tsvector('english', coalesce(title, '') || ' ' || coalesce(section, '') || ' ' || coalesce(content, '')) @@ plainto_tsquery('english', :query)
                      AND (:organization IS NULL OR organization ILIKE :organization)
                      AND (:agreement_type IS NULL OR agreement_type ILIKE :agreement_type)
                      AND (:domain IS NULL OR domain ILIKE :domain)
                      AND (:topic IS NULL OR topic ILIKE :topic)
                      AND (:tag IS NULL OR tags ILIKE :tag)
                      AND (:exclude_superseded = FALSE OR (superseded = FALSE AND terminated = FALSE))
                    LIMIT 40
                )
                SELECT c.id, c.organization, c.counterparty, c.agreement_type, c.domain,
                       c.title, c.section, c.parent_section, c.hierarchy_level,
                       c.definitions_ref, c.exceptions_ref, c.authority_class,
                       c.effective_date, c.superseded, c.terminated, c.superseded_by,
                       c.source_url, c.content, c.structured_slots, c.topic, c.tags, c.summary, c.embedding
                FROM commercial_clauses_vectors c
                WHERE c.id IN (SELECT id FROM vector_ranks UNION SELECT id FROM fts_ranks);
            """
            params = {
                "query_vector": vec_str,
                "query": query,
                "tenant_id": tenant_id,
                "organization": organization,
                "agreement_type": agreement_type,
                "domain": domain,
                "topic": topic,
                "tag": f"%{tag}%" if tag else None,
                "exclude_superseded": exclude_superseded,
            }
            results = db.execute(text(sql), params).fetchall()
            for r in results:
                raw_tags = []
                if getattr(r, "tags", None):
                    try:
                        raw_tags = json.loads(r.tags) if isinstance(r.tags, str) else list(r.tags)
                    except Exception:
                        raw_tags = [t.strip() for t in str(r.tags).split(",") if t.strip()]

                raw_candidates[r.id] = {
                    "id": r.id,
                    "organization": r.organization,
                    "counterparty": r.counterparty,
                    "agreement_type": r.agreement_type,
                    "domain": r.domain,
                    "title": r.title,
                    "section": r.section,
                    "parent_section": r.parent_section,
                    "hierarchy_level": r.hierarchy_level,
                    "definitions_ref": r.definitions_ref,
                    "exceptions_ref": r.exceptions_ref,
                    "authority_class": r.authority_class,
                    "effective_date": r.effective_date,
                    "superseded": r.superseded,
                    "terminated": r.terminated,
                    "superseded_by": r.superseded_by,
                    "source_url": r.source_url,
                    "content": r.content,
                    "structured_slots": r.structured_slots,
                    "topic": getattr(r, "topic", None),
                    "tags": raw_tags,
                    "summary": getattr(r, "summary", None),
                    "embedding": getattr(r, "embedding", None),
                }
        except Exception as e:
            logger.warning(f"PostgreSQL hybrid query fallback to ORM search: {e}")
            raw_candidates.clear()

    # 2. Fetch Candidates (SQLite or Fallback Path)
    if not raw_candidates:
        base_query = db.query(CommercialClauseVector).filter(CommercialClauseVector.tenant_id == tenant_id)
        if exclude_superseded:
            base_query = base_query.filter(
                CommercialClauseVector.superseded.is_(False),
                CommercialClauseVector.terminated.is_(False)
            )
        if organization:
            base_query = base_query.filter(CommercialClauseVector.organization.ilike(f"%{organization}%"))
        if agreement_type:
            base_query = base_query.filter(CommercialClauseVector.agreement_type.ilike(f"%{agreement_type}%"))
        if domain:
            base_query = base_query.filter(CommercialClauseVector.domain.ilike(f"%{domain}%"))
        if topic:
            base_query = base_query.filter(CommercialClauseVector.topic.ilike(f"%{topic}%"))
        if tag:
            base_query = base_query.filter(CommercialClauseVector.tags.ilike(f"%{tag}%"))

        all_clauses = base_query.all()
        for c in all_clauses:
            raw_tags = []
            if c.tags:
                try:
                    raw_tags = json.loads(c.tags) if isinstance(c.tags, str) else list(c.tags)
                except Exception:
                    raw_tags = [t.strip() for t in str(c.tags).split(",") if t.strip()]

            raw_candidates[c.id] = {
                "id": c.id,
                "organization": c.organization,
                "counterparty": c.counterparty,
                "agreement_type": c.agreement_type,
                "domain": c.domain,
                "title": c.title,
                "section": c.section,
                "parent_section": c.parent_section,
                "hierarchy_level": c.hierarchy_level,
                "definitions_ref": c.definitions_ref,
                "exceptions_ref": c.exceptions_ref,
                "authority_class": c.authority_class,
                "effective_date": c.effective_date,
                "superseded": c.superseded,
                "terminated": c.terminated,
                "superseded_by": c.superseded_by,
                "source_url": c.source_url,
                "content": c.content,
                "structured_slots": c.structured_slots,
                "topic": c.topic,
                "tags": raw_tags,
                "summary": c.summary,
                "embedding": c.embedding,
            }

    # 3. Deduplication by (agreement/organization, section, chunk_index)
    seen_entities = set()
    deduped_candidates = []
    for cand in raw_candidates.values():
        dedup_key = (
            cand.get("organization") or cand.get("agreement_type") or "default",
            cand.get("section") or cand.get("title") or "general",
            cand.get("chunk_index", 0)
        )
        if dedup_key not in seen_entities:
            seen_entities.add(dedup_key)
            deduped_candidates.append(cand)

    # 4. Single Unified Python Scorer
    query_words = set(re.findall(r'\w+', expanded_query.lower()))
    scored_list = []
    for cand in deduped_candidates:
        scored = score_retrieval_candidate(
            cand=cand,
            query_vector=query_vector,
            query_words=query_words,
            quoted_phrases=quoted_phrases,
            section_patterns=section_patterns,
            spotted_auths=spotted_auths,
            spotted_tags=spotted_tags
        )
        scored_list.append(scored)

    scored_list.sort(key=lambda x: x["score"], reverse=True)
    return scored_list[offset:offset + limit]



STOPWORDS = {
    "pursuant", "under", "section", "clause", "article", "exhibit", "lease",
    "shall", "will", "must", "with", "within", "that", "this", "from", "party",
    "parties", "each", "both", "have", "has", "been", "hereunder", "thereto",
    "accordance", "agreement", "contract", "customer", "vendor", "said", "such",
    "other", "upon", "into", "their", "about", "above", "below"
}

WORD_TO_NUM: dict[str, int] = {
    "zero": 0, "one": 1, "two": 2, "three": 3, "four": 4, "five": 5,
    "six": 6, "seven": 7, "eight": 8, "nine": 9, "ten": 10,
    "eleven": 11, "twelve": 12, "fifteen": 15, "twenty": 20,
    "twenty-four": 24, "twenty four": 24, "thirty": 30, "forty-five": 45,
    "forty five": 45, "sixty": 60, "ninety": 90, "hundred": 100,
    "thousand": 1000, "million": 1000000
}


def parse_spoken_number(text: str) -> float | None:
    """Parse English written numbers like 'thirty (30)', 'two million', 'Net 30'."""
    t = text.lower().strip()
    if t in WORD_TO_NUM:
        return float(WORD_TO_NUM[t])
    paren_m = re.search(r'\b(?:[a-z\-]+)\s*\((\d+(?:\.\d+)?)\)', t)
    if paren_m:
        return float(paren_m.group(1))
    if "million" in t:
        parts = t.split("million")[0].strip().split()
        if parts and parts[-1] in WORD_TO_NUM:
            return float(WORD_TO_NUM[parts[-1]] * 1000000)
    if "five hundred thousand" in t:
        return 500000.0
    return None


def normalize_money_val(val: Any) -> tuple[float | None, str]:
    """Extract numeric value and currency code ($ -> USD, € -> EUR, £ -> GBP)."""
    if isinstance(val, (int, float)):
        return float(val), "USD"
    s = str(val).strip()

    # 1. Search for currency symbol + amount
    m_sym = re.search(r'([\$€£])\s*([\d,]+(?:\.\d+)?)\s*([mMkK]\b)?', s)
    if m_sym:
        sym = m_sym.group(1)
        curr = "EUR" if sym == "€" else ("GBP" if sym == "£" else "USD")
        amt = float(m_sym.group(2).replace(",", ""))
        mult = (m_sym.group(3) or "").lower()
        if mult == "m":
            amt *= 1000000.0
        elif mult == "k":
            amt *= 1000.0
        return amt, curr

    # 2. Search for currency word + amount
    m_word = re.search(r'([\d,]+(?:\.\d+)?)\s*(dollars?|usd|euros?|eur|pounds?|gbp)\b', s, re.IGNORECASE)
    if m_word:
        amt = float(m_word.group(1).replace(",", ""))
        w = m_word.group(2).lower()
        curr = "EUR" if "eur" in w or "euro" in w else ("GBP" if "pound" in w or "gbp" in w else "USD")
        return amt, curr

    # 3. Direct number parse
    curr = "USD"
    if "€" in s or "eur" in s.lower():
        curr = "EUR"
    elif "£" in s or "gbp" in s.lower():
        curr = "GBP"

    spoken = parse_spoken_number(s)
    if spoken is not None:
        return spoken, curr

    clean_nums = re.findall(r'\b\d+(?:,\d{3})*(?:\.\d+)?\b', s)
    if clean_nums:
        try:
            return float(clean_nums[-1].replace(",", "")), curr
        except ValueError:
            pass
    return None, curr


def extract_rate_info(sentence: str) -> tuple[float | None, str | None]:
    """Extract interest percentage and its rate basis (%/month vs %/year)."""
    m = re.search(r'(\d+(?:\.\d+)?)\s*%\s*(per\s+month|monthly|apr|annual|per\s+annum)?', sentence, re.IGNORECASE)
    if not m:
        return None, None
    val = float(m.group(1))
    basis_str = (m.group(2) or "").lower()
    if any(w in basis_str for w in ("apr", "annual", "per annum")):
        basis = "%/year"
    elif any(w in basis_str for w in ("month", "monthly")):
        basis = "%/month"
    else:
        basis = "%"
    return val, basis


def verify_commercial_grounding(
    analysis_text: str,
    retrieved_clauses: list[dict[str, Any]],
    allow_refusal: bool = True
) -> tuple[bool, list[dict[str, Any]], str, dict[str, Any]]:
    """
    Verify commercial assertions and citations in generated text against retrieved clauses.
    Layered verification checker:
      1. Citation Resolution: section + instrument matching against retrieved controlling set.
      2. Superseded Check: detects inoperative / terminated instruments.
      3. Slot Normalization: type-safe comparison of numbers, currencies, and percentages.
      4. Partial Support: detects claims omitting required numerical terms on covered topics.
      5. Negation & Exception Check: detects flipped obligations or dropped carve-outs.
      6. Token Containment: substantive token coverage (non-stopwords).
    """
    if not analysis_text or not analysis_text.strip():
        return False, [], "Analysis text is empty.", {"pass_rate": 0.0}

    # Index known clauses by normalized section and instrument
    known_clauses_by_sec: dict[str, list[dict[str, Any]]] = {}
    for c in retrieved_clauses:
        sec = c.get("section")
        if sec:
            raw_k = sec.lower().strip()
            # Normalize prefix like "Exhibit B Section 2.1" -> "2.1"
            norm_sec = re.sub(
                r'^(?:(?:Exhibit\s+[A-Za-z\d]+(?:\s*\([A-Za-z0-9]+\))?|Article\s+[IVXLCDM\d]+|Lease)\s*,?\s*)?(?:Section|Clause|§|lease\s*§)\s*',
                '',
                sec,
                flags=re.IGNORECASE
            ).strip().lower()

            known_clauses_by_sec.setdefault(norm_sec, []).append(c)
            if raw_k != norm_sec:
                known_clauses_by_sec.setdefault(raw_k, []).append(c)

            # Also index sub-section if present, e.g. "section 2.1"
            sec_only = re.search(r'(?:section|clause|§)\s*([\w\.\-]+)', raw_k)
            if sec_only:
                s_id = sec_only.group(1).lower()
                if s_id != norm_sec:
                    known_clauses_by_sec.setdefault(s_id, []).append(c)

            # Alpha-numeric clean key
            clean_k = re.sub(r'[^\w\.]', '', raw_k)
            if clean_k not in (norm_sec, raw_k):
                known_clauses_by_sec.setdefault(clean_k, []).append(c)

    claim_records: list[dict[str, Any]] = []
    # Claim decomposition: split on sentence boundaries, semicolons, and newlines
    sentences = [s.strip() for s in re.split(r'(?<=[.!?;\n])\s+', analysis_text) if s.strip()]

    total_claims = 0
    supported_claims = 0
    unsupported_claims = 0
    invented_clauses = 0
    divergent_terms = 0
    superseded_terms = 0
    wrong_instruments = 0
    partial_supports = 0
    negated_obligations = 0
    ambiguous_citations = 0

    citation_pattern = re.compile(
        r'((?:(?:the\s+)?(?:\d{4}\s+)?(?:MSA|SOW|Statement\s+of\s+Work|Master\s+Agreement|Amendment(?:\s+No\.?\s*\d+)?|Exhibit\s+[A-Za-z\d]+(?:\s*\([A-Za-z0-9]+\))?|Article\s+[IVXLCDM\d]+|Lease)\s*,?\s*)?(?:Section|Clause|§)\s*[\w\.\-]+(?:\([a-zA-Z\d]+\))*|Exhibit\s+[A-Za-z\d]+(?:\s*\([A-Za-z0-9]+\))?|Lease\s*§\s*[\w\.\-]+)',
        re.IGNORECASE
    )

    for sentence in sentences:
        matches = list(citation_pattern.finditer(sentence))
        if not matches:
            continue

        for m in matches:
            total_claims += 1
            cited_raw = m.group(0)
            cited_clean = cited_raw.lower().strip()

            # Extract cited section identifier
            sec_match = re.search(r'(?:section|clause|§|lease\s*§)\s*([\w\.\-]+)', cited_clean)
            if sec_match:
                cited_sec_id = sec_match.group(1)
            else:
                # E.g. "Exhibit B"
                cited_sec_id = re.sub(r'^(?:the\s+)?', '', cited_clean)

            # Check if sentence cites a specific instrument
            cited_instrument = None
            if "sow" in cited_clean or "statement of work" in cited_clean:
                cited_instrument = "statement_of_work"
            elif "msa" in cited_clean or "master agreement" in cited_clean:
                cited_instrument = "master_services_agreement"
            elif "amendment" in cited_clean:
                cited_instrument = "amendment"
            elif "lease" in cited_clean:
                cited_instrument = "lease"
            elif "exhibit b" in cited_clean:
                cited_instrument = "exhibit b"
            elif "exhibit c" in cited_clean:
                cited_instrument = "exhibit c"

            # 1. Resolve matching clause in controlling set
            matching_candidates = (
                known_clauses_by_sec.get(cited_sec_id)
                or known_clauses_by_sec.get(f"section {cited_sec_id}")
                or known_clauses_by_sec.get(cited_clean)
                or []
            )

            if not matching_candidates:
                # Fallback substring match
                for k, cl_list in known_clauses_by_sec.items():
                    if cited_sec_id and (cited_sec_id == k or cited_sec_id in k.split()):
                        matching_candidates = cl_list
                        break

            if not matching_candidates:
                invented_clauses += 1
                unsupported_claims += 1
                claim_records.append({
                    "claim_id": f"claim_{total_claims}",
                    "sentence": sentence,
                    "cited_authority": cited_raw,
                    "status": "no_authority",
                    "failure_mode": "NO_AUTHORITY",
                    "details": f"Cited authority '{cited_raw}' does not exist in the retrieved commercial corpus.",
                    "evidence_span": None
                })
                continue

            # Instrument disambiguation / check
            matching_clause = None
            if cited_instrument:
                for cand in matching_candidates:
                    c_type = (cand.get("instrument_type") or cand.get("agreement_type") or "").lower()
                    c_title = (cand.get("agreement_title") or cand.get("title") or "").lower()
                    c_sec = (cand.get("section") or "").lower()
                    if (
                        (cited_instrument in c_type)
                        or (cited_instrument in c_title)
                        or (cited_instrument in c_sec)
                        or (cited_instrument == "statement_of_work" and any("sow" in f for f in (c_title, c_sec, c_type)))
                        or (cited_instrument == "master_services_agreement" and any("msa" in f for f in (c_title, c_sec, c_type)))
                    ):
                        matching_clause = cand
                        break

                if not matching_clause:
                    # Section exists, but in the WRONG instrument!
                    wrong_instruments += 1
                    unsupported_claims += 1
                    actual_inst = matching_candidates[0].get("agreement_title") or matching_candidates[0].get("agreement_type") or "other agreement"
                    claim_records.append({
                        "claim_id": f"claim_{total_claims}",
                        "sentence": sentence,
                        "cited_authority": cited_raw,
                        "status": "wrong_instrument",
                        "failure_mode": "WRONG_INSTRUMENT",
                        "details": f"Cited instrument '{cited_raw}' does not match governing document for this section (found in: '{actual_inst}').",
                        "evidence_span": matching_candidates[0].get("content", "")[:180] + "..."
                    })
                    continue
            else:
                # Ambiguous Citation Check: multiple distinct active agreements match the section without instrument qualifier
                active_cands = [c for c in matching_candidates if not c.get("superseded") and not c.get("terminated")]
                distinct_ags = set(
                    cand.get("agreement_id") or cand.get("agreement_title") or cand.get("title")
                    for cand in active_cands
                )
                if len(distinct_ags) > 1:
                    ambiguous_citations += 1
                    unsupported_claims += 1
                    claim_records.append({
                        "claim_id": f"claim_{total_claims}",
                        "sentence": sentence,
                        "cited_authority": cited_raw,
                        "status": "no_authority",
                        "failure_mode": "NO_AUTHORITY",
                        "details": f"Ambiguous citation: '{cited_raw}' matches {len(distinct_ags)} distinct agreements in controlling set without instrument qualification.",
                        "evidence_span": None
                    })
                    continue
                matching_clause = active_cands[0] if active_cands else matching_candidates[0]

            # 2. Check: Superseded / Inoperative
            if matching_clause.get("superseded") or matching_clause.get("terminated"):
                superseded_terms += 1
                unsupported_claims += 1
                claim_records.append({
                    "claim_id": f"claim_{total_claims}",
                    "sentence": sentence,
                    "cited_authority": cited_raw,
                    "status": "superseded",
                    "failure_mode": "SUPERSEDED",
                    "details": f"Authority '{cited_raw}' is superseded / inoperative (superseded by: {matching_clause.get('superseded_by', 'controlling agreement')}).",
                    "evidence_span": matching_clause.get("content", "")[:180] + "..."
                })
                continue

            # 3. Check: Negation and Carve-outs (NEGATED_OBLIGATION)
            sent_lower = sentence.lower()
            clause_content = matching_clause.get("content", "")
            clause_lower = clause_content.lower()

            # Negation polarity inversion
            is_claim_negated = bool(re.search(r'\b(?:shall\s+not\s+be\s+capped|is\s+not\s+capped|uncapped|without\s+cap|unlimited\s+liability|shall\s+exceed|not\s+apply)\b', sent_lower))
            is_clause_limiting = bool(re.search(r'\b(?:shall\s+be\s+capped|aggregate\s+liability\s+shall|in\s+no\s+event\s+shall|limited\s+to|shall\s+not\s+exceed)\b', clause_lower))
            if is_claim_negated and is_clause_limiting and "cap_amount" in (matching_clause.get("structured_slots") or {}):
                negated_obligations += 1
                unsupported_claims += 1
                claim_records.append({
                    "claim_id": f"claim_{total_claims}",
                    "sentence": sentence,
                    "cited_authority": cited_raw,
                    "status": "negated_obligation",
                    "failure_mode": "NEGATED_OBLIGATION",
                    "details": f"Asserted proposition inverts contractual liability limit in '{cited_raw}'.",
                    "evidence_span": clause_content[:180] + "..."
                })
                continue

            # Dropped carve-out check: clause has exceptions, but claim asserts absolute/uncarved cap
            clause_has_carveouts = "carve_outs" in (matching_clause.get("structured_slots") or {}) or "except" in clause_lower or "excluding" in clause_lower
            claim_drops_carveouts = bool(re.search(r'\b(?:for\s+all\s+claims\s+without\s+exception|without\s+exception|including\s+gross\s+negligence)\b', sent_lower))
            if clause_has_carveouts and claim_drops_carveouts:
                negated_obligations += 1
                unsupported_claims += 1
                claim_records.append({
                    "claim_id": f"claim_{total_claims}",
                    "sentence": sentence,
                    "cited_authority": cited_raw,
                    "status": "negated_obligation",
                    "failure_mode": "NEGATED_OBLIGATION",
                    "details": f"Asserted proposition in '{cited_raw}' drops or denies contractual carve-outs/exceptions.",
                    "evidence_span": clause_content[:180] + "..."
                })
                continue

            # Conditionals & Carve-outs: Handle "upon material breach", "except for", "notwithstanding", "unless pre-approved"
            clause_has_condition = bool(re.search(
                r'\b(?:except\s+for|except\s+in|excluding|subject\s+to|upon\s+material\s+breach|conditioned\s+upon|unless\s+pre-approved|except\s+for\s+pre-approved|notwithstanding)\b',
                clause_lower
            ))
            claim_is_unconditional = bool(re.search(
                r'\b(?:all\s+orders|every\s+order|without\s+exception|for\s+all\s+claims|in\s+all\s+cases|unconditionally|regardless\s+of)\b',
                sent_lower
            ))
            if clause_has_condition and claim_is_unconditional:
                negated_obligations += 1
                unsupported_claims += 1
                claim_records.append({
                    "claim_id": f"claim_{total_claims}",
                    "sentence": sentence,
                    "cited_authority": cited_raw,
                    "status": "negated_obligation",
                    "failure_mode": "NEGATED_OBLIGATION",
                    "details": f"Asserted proposition in '{cited_raw}' drops contractual condition or exception.",
                    "evidence_span": clause_content[:180] + "..."
                })
                continue

            # 4. Check: Structured slot extraction & type normalization
            _, sent_slots = extract_structured_slots(sentence)
            clause_slots = matching_clause.get("structured_slots") or {}
            if not clause_slots:
                _, clause_slots = extract_structured_slots(clause_content)

            # Currency check
            sent_amt, sent_curr = normalize_money_val(sentence)
            clause_cap_raw = clause_slots.get("cap_amount")
            if clause_cap_raw:
                clause_amt, clause_curr = normalize_money_val(clause_cap_raw)
                if sent_amt is not None and clause_amt is not None:
                    if sent_curr != clause_curr:
                        divergent_terms += 1
                        unsupported_claims += 1
                        claim_records.append({
                            "claim_id": f"claim_{total_claims}",
                            "sentence": sentence,
                            "cited_authority": cited_raw,
                            "status": "unit_mismatch",
                            "failure_mode": "UNIT_MISMATCH",
                            "details": f"Currency mismatch: asserted '{sent_curr}' diverges from contract authority '{clause_curr}'.",
                            "evidence_span": clause_content[:180] + "..."
                        })
                        continue

            # Interest rate basis check (e.g. 1.5% per month vs 18% APR)
            sent_rate, sent_basis = extract_rate_info(sentence)
            if "late_interest_pct" in clause_slots and sent_rate is not None:
                clause_rate_raw = get_slot_val(clause_slots["late_interest_pct"])
                if sent_basis == "%/year" and clause_rate_raw <= 5.0:
                    divergent_terms += 1
                    unsupported_claims += 1
                    claim_records.append({
                        "claim_id": f"claim_{total_claims}",
                        "sentence": sentence,
                        "cited_authority": cited_raw,
                        "status": "unit_mismatch",
                        "failure_mode": "UNIT_MISMATCH",
                        "details": f"Rate unit mismatch: asserted {sent_rate}% APR diverges from contract monthly rate ({clause_rate_raw}% per month).",
                        "evidence_span": clause_content[:180] + "..."
                    })
                    continue

            # Numerical slot comparison
            slot_divergence = False
            divergence_reason = ""
            for skey in ("net_days", "uptime_pct", "late_interest_pct", "cap_period_months", "cap_amount", "notice_hours", "notice_days", "cure_days", "credit_pct"):
                if skey in sent_slots and skey in clause_slots:
                    val_sent_prim = get_slot_val(sent_slots[skey])
                    val_clause_prim = get_slot_val(clause_slots[skey])
                    # Normalize types: int vs float, numeric float comparison
                    try:
                        norm_sent = float(val_sent_prim)
                        norm_clause = float(val_clause_prim)
                        is_diff = abs(norm_sent - norm_clause) > 1e-4
                    except (ValueError, TypeError):
                        is_diff = (str(val_sent_prim).lower() != str(val_clause_prim).lower())

                    if is_diff:
                        slot_divergence = True
                        divergence_reason = f"Asserted slot '{skey}={val_sent_prim}' diverges from contract authority '{skey}={val_clause_prim}'."
                        break

            if slot_divergence:
                divergent_terms += 1
                unsupported_claims += 1
                claim_records.append({
                    "claim_id": f"claim_{total_claims}",
                    "sentence": sentence,
                    "cited_authority": cited_raw,
                    "status": "slot_mismatch",
                    "failure_mode": "SLOT_MISMATCH",
                    "details": divergence_reason,
                    "evidence_span": clause_content[:180] + "..."
                })
                continue

            # 5. Check: Partial support (topic right, but critical slot missing)
            sent_without_sec = re.sub(
                r'(?:(?:the\s+)?(?:\d{4}\s+)?(?:MSA|SOW|Statement\s+of\s+Work|Master\s+Agreement|Amendment(?:\s+No\.?\s*\d+)?|Exhibit\s+[A-Za-z\d]+(?:\s*\([A-Za-z0-9]+\))?|Article\s+[IVXLCDM\d]+|Lease)\s*,?\s*)?(?:Section|Clause|§|lease\s*§)\s*[\w\.\-]+(?:\([a-zA-Z\d]+\))*',
                '',
                sent_lower
            )
            is_partial = False
            missing_slot_name = None
            if "net_days" in clause_slots and "net_days" not in sent_slots:
                # Did sentence make payment claims without stating the required days?
                if any(w in sent_without_sec for w in ("pay", "payment", "invoice", "remit")) and not re.search(r'\b(?:net\s*\d+|\d+\s*days?)\b', sent_without_sec):
                    is_partial = True
                    missing_slot_name = "net_days"
            elif "cap_amount" in clause_slots and "cap_amount" not in sent_slots and sent_amt is None:
                if any(w in sent_without_sec for w in ("liability", "cap", "limit", "capped")) and not re.search(r'[\$€£]', sent_without_sec):
                    is_partial = True
                    missing_slot_name = "cap_amount"

            if is_partial:
                partial_supports += 1
                unsupported_claims += 1
                claim_records.append({
                    "claim_id": f"claim_{total_claims}",
                    "sentence": sentence,
                    "cited_authority": cited_raw,
                    "status": "partial_support",
                    "failure_mode": "PARTIAL_SUPPORT",
                    "details": f"Clause '{cited_raw}' addresses this topic, but asserted claim omits required numerical threshold '{missing_slot_name}'.",
                    "evidence_span": clause_content[:180] + "..."
                })
                continue

            # 6. Check: Substantive token containment & Strict Slot/Span Requirement for Numbers
            body_digits = re.findall(r'\b\d+(?:\.\d+)?%?\b', sent_without_sec)
            has_numeric_assertion = bool(body_digits) or any(s in sent_slots for s in ("net_days", "uptime_pct", "late_interest_pct", "cap_amount", "notice_hours", "notice_days", "cure_days", "credit_pct")) or bool(re.search(r'[\$€£]', sent_without_sec))

            has_slot_match = bool(set(sent_slots.keys()).intersection(clause_slots.keys()))

            if has_numeric_assertion:
                # Invariant (Priority 4 & 5): Numeric claims REQUIRE slot match or exact span containment in the clause!
                # Lexical token overlap CANNOT substantiate numeric claims.
                span_contained = False
                for d in body_digits:
                    clean_d = d.strip("%")
                    if clean_d in clause_content:
                        span_contained = True
                        break

                if not has_slot_match and not span_contained:
                    divergent_terms += 1
                    unsupported_claims += 1
                    claim_records.append({
                        "claim_id": f"claim_{total_claims}",
                        "sentence": sentence,
                        "cited_authority": cited_raw,
                        "status": "slot_mismatch",
                        "failure_mode": "SLOT_MISMATCH",
                        "details": f"Numeric claim in '{cited_raw}' requires slot match or span containment; asserted values not found in governing clause.",
                        "evidence_span": clause_content[:180] + "..."
                    })
                    continue

            sent_words = [w for w in re.findall(r'[a-zA-Z]{3,}', sent_lower) if w not in STOPWORDS]
            clause_words = set(w for w in re.findall(r'[a-zA-Z]{3,}', clause_lower) if w not in STOPWORDS)
            substantive_overlap = [w for w in sent_words if w in clause_words]

            is_substantiated = (
                has_slot_match
                or (len(sent_words) > 0 and len(substantive_overlap) / len(sent_words) >= 0.40)
                or len(substantive_overlap) >= 2
            )

            if is_substantiated and (len(substantive_overlap) > 0 or has_slot_match):
                supported_claims += 1
                span_match = clause_content[:200] + ("..." if len(clause_content) > 200 else "")
                claim_records.append({
                    "claim_id": f"claim_{total_claims}",
                    "sentence": sentence,
                    "cited_authority": cited_raw,
                    "status": "verified_grounded",
                    "failure_mode": None,
                    "details": f"Substantiated by {matching_clause.get('title', cited_raw)}.",
                    "evidence_span": span_match
                })
            else:
                divergent_terms += 1
                unsupported_claims += 1
                claim_records.append({
                    "claim_id": f"claim_{total_claims}",
                    "sentence": sentence,
                    "cited_authority": cited_raw,
                    "status": "slot_mismatch",
                    "failure_mode": "SLOT_MISMATCH",
                    "details": f"Clause '{cited_raw}' exists, but text diverges significantly from the asserted terms.",
                    "evidence_span": clause_content[:180] + "..."
                })

    if total_claims == 0:
        pass_rate = 100.0
        advisory_md = "> 🛡️ **Assertion Grounding Status**: General descriptive text without explicit section citations."
    else:
        pass_rate = round((supported_claims / total_claims) * 100.0, 1)
        if pass_rate < 100.0:
            advisory_md = (
                f"> ⚠️ **COMMERCIAL GROUNDING WARNING**: Only {supported_claims}/{total_claims} assertions ({pass_rate}%) "
                f"are verified against the governing contract graph. "
                f"{invented_clauses} invented clause(s), {divergent_terms} divergent term(s), {superseded_terms} superseded term(s), "
                f"{wrong_instruments} wrong instrument(s), {partial_supports} partial support(s), {negated_obligations} negated obligation(s), "
                f"and {ambiguous_citations} ambiguous citation(s) detected."
            )
        else:
            advisory_md = (
                f"> 🛡️ **COMMERCIAL GROUNDING VERIFIED**: 100% of asserted terms ({total_claims}/{total_claims}) "
                f"are fully supported by active, controlling contractual authorities."
            )

    stats = {
        "total_claims": total_claims,
        "supported_claims": supported_claims,
        "unsupported_claims": unsupported_claims,
        "wrong_instruments": wrong_instruments,
        "slot_mismatches": sum(1 for c in claim_records if c.get("failure_mode") == "SLOT_MISMATCH"),
        "unit_mismatches": sum(1 for c in claim_records if c.get("failure_mode") == "UNIT_MISMATCH"),
        "negated_obligations": negated_obligations,
        "partial_supports": partial_supports,
        "superseded": superseded_terms,
        "superseded_terms": superseded_terms,
        "no_authorities": invented_clauses + ambiguous_citations,
        "invented_clauses": invented_clauses,
        "divergent_terms": sum(1 for c in claim_records if c.get("failure_mode") in ("SLOT_MISMATCH", "UNIT_MISMATCH")),
        "ambiguous_citations": ambiguous_citations,
        "pass_rate": pass_rate
    }
    is_grounded = (unsupported_claims == 0)
    return is_grounded, claim_records, advisory_md, stats


def generate_executive_brief(
    deal_title: str,
    context_facts: str,
    clauses: list[dict[str, Any]],
    counterparty: str | None = None,
    deal_type: str | None = None,
    deal_code: str | None = None,
    deal_id: int | None = None,
    db: Any = None,
    model: str | None = None,
    temperature: float = 0.1,
    tenant_id: str = "org_default",
) -> tuple[str, dict[str, Any], list[dict[str, Any]]]:
    """
    Generate an executive commercial brief grounded in retrieved authorities.
    Refuses drafting if:
      - No authorities exist (CANNOT_DRAFT_WITHOUT_AUTHORITIES)
      - All authorities are superseded (REFUSAL_ALL_AUTHORITIES_SUPERSEDED)
    Persists GroundingAudit report to database if db and deal_id are provided.
    """
    # 1. Guardrail Refusal: No Authorities
    if not clauses:
        refusal_msg = (
            "CANNOT_DRAFT_WITHOUT_AUTHORITIES: Insufficient governing contracts, amendments, or corporate policies "
            "found in the local commercial graph to substantiate this deal review. "
            "Please ingest the governing Master Agreement, SLA, or SOW before requesting executive synthesis."
        )
        stats = {
            "total_claims": 0,
            "supported_claims": 0,
            "unsupported_claims": 0,
            "invented_clauses": 0,
            "divergent_terms": 0,
            "superseded_terms": 0,
            "pass_rate": 0.0,
            "refusal_reason": "CANNOT_DRAFT_WITHOUT_AUTHORITIES"
        }
        return refusal_msg, stats, []

    # 2. Guardrail Refusal: All Authorities Superseded
    if all(c.get("superseded", False) or c.get("terminated", False) for c in clauses):
        refusal_msg = (
            "REFUSAL_ALL_AUTHORITIES_SUPERSEDED: All governing authorities retrieved for this commercial matter "
            "are superseded, terminated, or expired instruments. "
            "Executive briefs cannot be drafted against inoperative terms. Please ingest active controlling agreements."
        )
        stats = {
            "total_claims": 0,
            "supported_claims": 0,
            "unsupported_claims": 0,
            "invented_clauses": 0,
            "divergent_terms": 0,
            "superseded_terms": len(clauses),
            "pass_rate": 0.0,
            "refusal_reason": "REFUSAL_ALL_AUTHORITIES_SUPERSEDED"
        }
        return refusal_msg, stats, []

    # 3. Guardrail Refusal: Contract Conflicts Detected across Active Authorities
    topic_clauses: dict[str, list[dict[str, Any]]] = {}
    for c in clauses:
        if not c.get("superseded", False) and not c.get("terminated", False):
            t = c.get("topic") or "GENERAL_COMMERCIAL"
            if t != "GENERAL_COMMERCIAL":
                topic_clauses.setdefault(t, []).append(c)

    conflicting_topic = None
    diverging_details = None
    for t, t_cls in topic_clauses.items():
        if len(t_cls) >= 2:
            first_slots = t_cls[0].get("structured_slots") or {}
            for other_c in t_cls[1:]:
                other_slots = other_c.get("structured_slots") or {}
                for k in ("net_days", "late_interest_pct", "uptime_pct", "cap_period_months", "notice_hours"):
                    if k in first_slots and k in other_slots:
                        val1 = get_slot_val(first_slots[k])
                        val2 = get_slot_val(other_slots[k])
                        if val1 != val2:
                            conflicting_topic = t
                            diverging_details = f"{k}: {val1} in '{t_cls[0].get('title')}' vs {val2} in '{other_c.get('title')}'"
                            break
                if conflicting_topic:
                    break
        if conflicting_topic:
            break

    if conflicting_topic:
        refusal_msg = (
            f"CANNOT_DRAFT_WITH_ACTIVE_CONFLICTS: Contract conflict detected on topic '{conflicting_topic}' "
            f"between operative agreements ({diverging_details}). "
            f"KruschBiz strictly refuses to synthesize an executive brief while live controlling terms diverge. "
            f"Please run 'resolve_controlling_clause' or execute an amendment to harmonize the conflicting terms."
        )
        stats = {
            "total_claims": 0,
            "supported_claims": 0,
            "unsupported_claims": 0,
            "invented_clauses": 0,
            "divergent_terms": 1,
            "superseded_terms": 0,
            "pass_rate": 0.0,
            "refusal_reason": "CANNOT_DRAFT_WITH_ACTIVE_CONFLICTS",
            "conflict_details": diverging_details
        }
        return refusal_msg, stats, []

    model_name = model or settings.OLLAMA_LLM_MODEL
    authorities_text = ""
    for idx, c in enumerate(clauses[:5], 1):
        authorities_text += (
            f"[{idx}] {c.get('agreement_type')} | {c.get('section', 'General')} ({c.get('title', '')}):\n"
            f"{c.get('content', '')}\n\n"
        )

    system_prompt = (
        "You are an executive commercial counsel and corporate deal strategist. "
        "Your task is to draft a rigorous, balanced Executive Commercial Memorandum. "
        "Strict Rule: Every factual obligation, cap, SLA metric, and penalty MUST be explicitly cited to one of the "
        "governing authorities provided below (e.g. 'Pursuant to Section 4.1...'). "
        "Never invent sections or obligations not present in the authorities."
    )

    user_prompt = f"""
TRANSACTION: {deal_title}
COUNTERPARTY: {counterparty or 'Counterparty'}
TYPE: {deal_type or 'Commercial Transaction'}
BACKGROUND / DEAL FACTS:
{context_facts}

GOVERNING AUTHORITIES:
{authorities_text}

Draft the Executive Commercial Memorandum with 4 sections:
I. KEY COMMERCIAL TERMS & TRANSACTION OVERVIEW
II. MATERIAL RISK EXPOSURE & CARVE-OUTS
III. OPERATIONAL, SLA & COMPLIANCE ALIGNMENT
IV. STRATEGIC RECOMMENDATIONS & REDLINE PRIORITIES
"""

    analysis_text = None
    try:
        with httpx.Client(timeout=settings.LLM_TIMEOUT) as client:
            resp = client.post(
                f"{settings.OLLAMA_BASE_URL}/api/generate",
                json={
                    "model": model_name,
                    "prompt": user_prompt,
                    "system": system_prompt,
                    "stream": False,
                    "options": {"temperature": temperature}
                }
            )
            if resp.status_code == 200:
                analysis_text = resp.json().get("response")
    except Exception as e:
        logger.warning(f"Ollama generation unavailable ({e}). Using deterministic executive template.")

    if not analysis_text:
        c0 = clauses[0]
        sec0 = c0.get("section", "Section 1.1")
        title0 = c0.get("title", "Governing Agreement")

        analysis_text = f"""# EXECUTIVE COMMERCIAL MEMORANDUM

## I. KEY COMMERCIAL TERMS & TRANSACTION OVERVIEW
The proposed transaction '{deal_title}' involves counterparty {counterparty or 'the designated vendor'} under {deal_type or 'a Master Services Agreement'}.
Pursuant to {sec0} ({title0}), the foundational commercial structure establishes binding obligations between the parties. Key milestones and baseline deliverables align with the provisions set forth in the governing documentation.

## II. MATERIAL RISK EXPOSURE & CARVE-OUTS
A critical review of the risk architecture indicates significant exposure requiring executive attention. Under {sec0}, liability limitations and indemnification thresholds govern the financial exposure. Carve-outs for gross negligence, willful misconduct, and breach of confidentiality must be strictly preserved to protect corporate interests against uncapped exposure.

## III. OPERATIONAL, SLA & COMPLIANCE ALIGNMENT
Operational parameters demand strict enforcement of service delivery benchmarks. In accordance with {sec0}, performance metrics, maintenance schedules, and audit verification windows require continuous monitoring. Any divergence between operational actuals and agreed terms triggers formal remedy mechanisms.

## IV. STRATEGIC RECOMMENDATIONS & REDLINE PRIORITIES
1. **Preserve Carve-Out Invariants**: Maintain uncapped exposure exceptions under {sec0}.
2. **Harmonize Invoicing Benchmarks**: Verify payment milestones and credit calculations prior to execution.
3. **Audit Execution**: Exercise scheduled verification rights to validate compliance with data security and SLA thresholds.
"""

    is_grounded, claims, advisory, stats = verify_commercial_grounding(analysis_text, clauses)

    proposed_count = 0
    if db is not None:
        try:
            from .db import AgreementRelation
            proposed_count = db.query(AgreementRelation).filter(
                AgreementRelation.tenant_id == tenant_id,
                AgreementRelation.status == "proposed"
            ).count()
        except Exception:
            pass

    stats["proposed_links_pending"] = proposed_count

    if db is not None and deal_id is not None:
        try:
            report = CommercialGroundingReport(
                tenant_id=tenant_id,
                deal_id=deal_id,
                total_claims=stats.get("total_claims", 0),
                supported_claims=stats.get("supported_claims", 0),
                unsupported_claims=stats.get("unsupported_claims", 0),
                invented_clauses=stats.get("invented_clauses", 0),
                divergent_terms=stats.get("divergent_terms", 0),
                superseded_terms=stats.get("superseded_terms", 0),
                pass_rate=stats.get("pass_rate", 100.0),
                claims_json=json.dumps(claims),
                advisory_markdown=advisory
            )
            db.add(report)
            db.commit()
        except Exception as e:
            logger.warning(f"Failed to persist grounding report for deal {deal_id}: {e}")

    banner = ""
    if proposed_count > 0:
        banner = f"> ⚠️ **CONTROLLING CLAUSE UNCERTAIN; {proposed_count} proposed relation link(s) pending human review.**\n\n"

    full_output = f"{banner}{analysis_text}\n\n{advisory}\n\n---\n*{COMMERCIAL_DISCLAIMER}*"
    return full_output, stats, claims


def retrieve_deal_evidence(
    db: Session,
    deal_id: int,
    text_query: str | None = None,
    tag: str | None = None,
    topic: str | None = None,
    limit: int = 10,
    doc_type: str | None = None,
    tenant_id: str = "org_default"
) -> list[dict[str, Any]]:
    """
    Search deal room exhibits, vendor proposals, redlines, and commercial attachments
    strictly within a single deal matter.
    Combines dense embeddings, lexical matching, canonical topic filtering, and commercial semantic tags.
    Guarantees strict tenant and deal boundary isolation.
    """
    query = db.query(DealEvidence).filter(
        DealEvidence.deal_id == deal_id,
        DealEvidence.tenant_id == tenant_id
    )

    if doc_type:
        query = query.filter(DealEvidence.doc_type == doc_type)
    if topic:
        query = query.filter(DealEvidence.topic.ilike(f"%{topic}%"))
    if tag:
        clean_tag = tag.lower().strip()
        query = query.filter(DealEvidence.tags.ilike(f"%{clean_tag}%"))

    rows = query.all()
    if not rows:
        return []

    def _format_record(r: DealEvidence, score_val: float = 1.0) -> dict[str, Any]:
        tags_list: list[str] = []
        if r.tags:
            try:
                tags_list = json.loads(r.tags) if isinstance(r.tags, str) else list(r.tags)
            except Exception:
                tags_list = [t.strip() for t in str(r.tags).split(",") if t.strip()]
        return {
            "id": r.id,
            "deal_id": r.deal_id,
            "tenant_id": r.tenant_id,
            "filename": r.filename,
            "doc_type": r.doc_type,
            "page_number": r.page_number,
            "section_locator": r.section_locator,
            "chunk_index": r.chunk_index,
            "content": r.content,
            "tags": tags_list,
            "summary": r.summary,
            "topic": r.topic,
            "similarity": round(float(score_val), 4),
            "created_at": r.created_at.isoformat() if r.created_at else None
        }

    if not text_query or not text_query.strip():
        return [_format_record(r, 1.0) for r in rows[:limit]]

    # Dense and lexical scoring
    q_vec = None
    try:
        q_vec = get_embedding(text_query)
    except Exception as e:
        logger.warning(f"Embedding error for deal evidence query: {e}")

    norm_q = math.sqrt(sum(a * a for a in q_vec)) if q_vec else 0.0
    q_tokens = set(re.findall(r'\b[a-zA-Z0-9\.\-]{3,}\b', text_query.lower()))

    scored_results = []
    for r in rows:
        cos_sim = 0.0
        if q_vec and r.embedding:
            try:
                emb = json.loads(r.embedding) if isinstance(r.embedding, str) else r.embedding
                dot = sum(a * b for a, b in zip(q_vec, emb))
                norm_e = math.sqrt(sum(b * b for b in emb))
                if norm_q > 0 and norm_e > 0:
                    cos_sim = dot / (norm_q * norm_e)
            except Exception:
                cos_sim = 0.0

        lex_score = 0.0
        tag_boost = 0.0
        if q_tokens:
            tags_str = r.tags or ""
            summary_str = r.summary or ""
            doc_text = f"{r.filename} {r.section_locator or ''} {summary_str} {tags_str} {r.content}".lower()
            matches = sum(1 for t in q_tokens if t in doc_text)
            lex_score = min(1.0, matches / max(1, len(q_tokens)))

            # Tag boost
            for t in q_tokens:
                if t in tags_str.lower():
                    tag_boost = max(tag_boost, 0.2)

        score = (0.6 * cos_sim) + (0.25 * lex_score) + (0.15 * tag_boost)
        scored_results.append((score, r))

    scored_results.sort(key=lambda x: x[0], reverse=True)
    return [_format_record(r, s) for s, r in scored_results[:limit]]
