"""
src/backend/rag.py
==================
Commercial RAG, hybrid retrieval, authority hierarchy weighting,
and assertion-level proposition grounding engine.
Features:
  - Hybrid dense ANN (pgvector / cosine) + full-text lexical search with Reciprocal Rank Fusion
  - Hierarchical authority weighting and explainable ranking breakdown
  - Assertion-level proposition grounding scanner with span overlap + structured slot match
  - Multi-failure taxonomy: INVENTED_CLAUSE, DIVERGENT_TERM, SUPERSEDED_TERM, VERIFIED
  - Refusal guardrails: CANNOT_DRAFT_WITHOUT_AUTHORITIES, REFUSAL_ALL_AUTHORITIES_SUPERSEDED
"""

from __future__ import annotations

import hashlib
import json
import logging
import math
import re
import threading
from collections import OrderedDict
from typing import Any

import httpx
from sqlalchemy import text
from sqlalchemy.orm import Session

from .config import settings
from .db import CommercialClauseVector, CommercialGroundingReport, DealEvidence
from .taxonomy import CANONICAL_TOPICS, extract_structured_slots

logger = logging.getLogger("kruschbiz.rag")

COMMERCIAL_DISCLAIMER = (
    "DISCLAIMER: This analysis was generated by KruschBiz, an offline, air-gapped corporate intelligence engine. "
    "This document is provided strictly for executive review, commercial risk spotting, and deal diligence. "
    "It does NOT constitute formal legal opinion or replace certified legal counsel. "
    "Admitted counsel and corporate officers must independently verify all contractual terms, indemnities, "
    "and regulatory commitments prior to execution or formal reliance."
)

AUTHORITY_WEIGHTS = {
    "governing_agreement": 1.25,
    "amendment_addendum": 1.20,
    "statement_of_work": 1.10,
    "corporate_policy": 1.00,
    "regulatory_framework": 0.95,
    "commercial_code": 0.90,
    "secondary_guideline": 0.80,
}

COMMERCIAL_ISSUE_RULES: list[dict[str, Any]] = [
    {
        "issue": "Payment Terms & Invoicing Due Date",
        "domain": "Procurement & Invoicing",
        "governing_authorities": "Section 4.1",
        "keywords": [
            r"\bpayment\s+deadline\b", r"\binvoice\s+date\b", r"\bnet\s*(?:30|45)\b",
            r"\bundisputed\s+(?:amounts?|charges?|invoices?)\b", r"\bach\b", r"\bwire\s+transfer\b",
            r"\bmethod\s+of\s+payment\b", r"\bdispute\s+notice\b", r"\bstandard\s+payment\b"
        ],
        "commercial_terms": "Section 4.1 Payment Terms invoicing undisputed amount Net 30 days ACH wire transfer good faith dispute notice"
    },
    {
        "issue": "Late Payment Penalties & Suspension of Service",
        "domain": "Procurement & Invoicing",
        "governing_authorities": "Section 4.2",
        "keywords": [
            r"\boverdue\b", r"\blate\s+(?:fee|payment|interest)\b", r"\b1\.5%?\b",
            r"\bsuspend\b", r"\bsuspending\s+services?\b", r"\bdelinquent\b",
            r"\bten\s*\(10\)\s*business\s+days\b", r"\bhow\s+many\s+business\s+days\s+notice\b"
        ],
        "commercial_terms": "Section 4.2 Late Payment Penalties late interest 1.5 percent per month suspend cloud service ten 10 business days prior written notice"
    },
    {
        "issue": "Mutual Limitation of Liability Cap",
        "domain": "Risk & Indemnification",
        "governing_authorities": "Section 10.1",
        "keywords": [
            r"\blimitation\s+of\s+liability\b", r"\bliability\s+cap\b", r"\bconsequential\s+damages\b",
            r"\btwelve\s*\(12\)\s*months\b", r"\b12\s+months\b", r"\bfees\s+paid\b",
            r"\baggregate\s+liability\b", r"\bcap\s+on\s+damages\b"
        ],
        "commercial_terms": "Section 10.1 Limitation of Liability aggregate liability twelve 12 months preceding incident fees paid lost profits indirect damages"
    },
    {
        "issue": "Uncapped Liability Carve-Outs and Exclusions",
        "domain": "Risk & Indemnification",
        "governing_authorities": "Section 10.2",
        "keywords": [
            r"\bcarve[\s-]?outs?\b", r"\buncapped\s+liability\b", r"\bgross\s+negligence\b",
            r"\bwillful\s+misconduct\b", r"\bbreach\s+of\s+confidentiality\b", r"\bexclusions?\s+from\s+cap\b",
            r"\bexceptions?\s+to\s+liability\b", r"\bnot\s+apply\s+to\b"
        ],
        "commercial_terms": "Section 10.2 Carve-outs and Exclusions gross negligence willful misconduct intentional fraud breach confidentiality Section 8"
    },
    {
        "issue": "Mutual Indemnification for Third-Party IP Claims",
        "domain": "Risk & Indemnification",
        "governing_authorities": "Section 11.1",
        "keywords": [
            r"\bindemnif(?:y|ication|ied)\b", r"\bhold\s+harmless\b", r"\bdefend\b",
            r"\bpatent\s+infringement\b", r"\bcopyright\s+infringement\b", r"\bthird[\s-]?party\s+claims?\b",
            r"\bsole\s+control\s+of\s+defense\b", r"\bprompt\s+written\s+notice\b"
        ],
        "commercial_terms": "Section 11.1 Mutual Indemnification patent copyright trademark infringement prompt written notice sole control defense"
    },
    {
        "issue": "CloudScale SLA Monthly Uptime Percentage",
        "domain": "Service Levels & Operations",
        "governing_authorities": "Exhibit B (SLA) Section 2.1",
        "keywords": [
            r"\buptime\s+percentage\b", r"\b99\.9%?\b", r"\bavailability\s+commitment\b",
            r"\boperational\s+due\s+diligence\b", r"\bhealth\s+probes\b", r"\bhttp\s*200\b"
        ],
        "commercial_terms": "Exhibit B Section 2.1 Availability Commitment Monthly Uptime Percentage 99.9% availability external health probes"
    },
    {
        "issue": "CloudScale SLA Maintenance Window Exclusions",
        "domain": "Service Levels & Operations",
        "governing_authorities": "Exhibit B (SLA) Section 2.2",
        "keywords": [
            r"\bscheduled\s+maintenance\b", r"\bmaintenance\s+window\b", r"\bsundays?\b",
            r"\b01:00\b", r"\b05:00\b", r"\b48\s+hours\b", r"\bforty-eight\s+\(48\)\s+hours\b"
        ],
        "commercial_terms": "Exhibit B Section 2.2 Maintenance Exclusions scheduled maintenance weekly maintenance window Sundays 01:00-05:00 UTC forty-eight 48 hours notice"
    },
    {
        "issue": "CloudScale SLA Service Credit Remedies",
        "domain": "Service Levels & Operations",
        "governing_authorities": "Exhibit B (SLA) Section 2.3",
        "keywords": [
            r"\bservice\s+credits?\b", r"\bcredit\s+percentage\b", r"\bunscheduled\s+outage\b",
            r"\b97\.5%?\b", r"\b93\.8%?\b", r"\bsole\s+and\s+exclusive\s+remedy\b",
            r"\b10%\s+credit\b", r"\b25%\s+credit\b", r"\b50%\s+credit\b"
        ],
        "commercial_terms": "Exhibit B Section 2.3 Service Credits credit percentage 95.0% to 98.99% 25% credit less than 95.0% 50% credit exclusive remedy"
    },
    {
        "issue": "Data Protection Addendum & SOC2 Type II Certification",
        "domain": "Security & Data Privacy",
        "governing_authorities": "Exhibit C (DPA) Section 3.1",
        "keywords": [
            r"\bsoc\s*2\b", r"\btype\s*ii\b", r"\baicpa\b", r"\bsecurity\s+standards?\b",
            r"\bannual\s+independent\b", r"\bauditor['’]?s?\s+report\b", r"\bhow\s+often\b"
        ],
        "commercial_terms": "Exhibit C Section 3.1 Security Standards AICPA SOC 2 Type II annual independent auditor report"
    },
    {
        "issue": "Data Protection Addendum 24-Hour Breach Notification",
        "domain": "Security & Data Privacy",
        "governing_authorities": "Exhibit C (DPA) Section 3.4",
        "keywords": [
            r"\bsecurity\s+incident\b", r"\bbreach\s+notification\b", r"\b24\s+hours?\b",
            r"\btwenty-four\s*\(24\)\s*hours?\b", r"\bpersonal\s+data\b", r"\bdata\s+breach\b",
            r"\bunauthorized\s+access\b", r"\bdaily\s+status\s+briefings\b"
        ],
        "commercial_terms": "Exhibit C Section 3.4 Security Incident Notification twenty-four 24 hours email telephone daily briefings unauthorized access"
    },
    {
        "issue": "Corporate Delegated Authority Approval Thresholds",
        "domain": "Corporate Governance & Delegated Authority",
        "governing_authorities": "Article IV Section 4.3",
        "keywords": [
            r"\bdelegated\s+authority\b", r"\bsignature\s+authorization\b", r"\bapproval\s+limits?\b",
            r"\bboard\s+of\s+directors\b", r"\bboard\s+approval\b", r"\$1,?000,?000\b",
            r"\bexceeding\s+\$1,?000,?000\b", r"\$250,?000\b", r"\$50,?000\b"
        ],
        "commercial_terms": "Article IV Section 4.3 Delegated Authority Thresholds signature limits Board Directors 1000000 CEO CFO 250000 VP 50000 Director"
    },
    {
        "issue": "Commercial Office Lease NNN Operating Expenses & CAM",
        "domain": "Real Estate & Leasing",
        "governing_authorities": "Lease § 5.2",
        "keywords": [
            r"\boperating\s+expenses\b", r"\bcam\b", r"\bcommon\s+area\s+maintenance\b",
            r"\btriple\s+net\b", r"\bnnn\b", r"\bpro\s+rata\s+share\b", r"\b14\.2%?\b",
            r"\badditional\s+rent\b", r"\bcapital\s+expenditures\b", r"\bmortgage\s+interest\b"
        ],
        "commercial_terms": "Lease Section 5.2 Operating Expenses CAM Common Area Maintenance Pro Rata Share 14.2 percent capital expenditures mortgage interest exclusions"
    },
    {
        "issue": "Commercial Office Lease Annual CAM Audit Rights",
        "domain": "Real Estate & Leasing",
        "governing_authorities": "Lease § 5.4",
        "keywords": [
            r"\bcam\s+audit\b", r"\baudit\s+rights?\b", r"\baudit\s+landlord\b",
            r"\bbooks\s+and\s+records\b", r"\bwithin\s+ninety\s+\(90\)\s+days\b",
            r"\bovercharge\s+exceeding\s+five\s+percent\b", r"\bhow\s+much\s+advance\s+notice\b"
        ],
        "commercial_terms": "Lease Section 5.4 CAM Audit Rights examine audit books 90 days ten 10 business days advance notice overcharge exceeding 5 percent"
    }
]


def expand_commercial_query(text_content: str) -> tuple[str, list[dict[str, str]]]:
    """
    Spot commercial issues from natural language inquiries, extracting structured slots
    and synthesizing canonical search terms.
    """
    if not text_content or not text_content.strip():
        return text_content, []

    spotted: list[dict[str, str]] = []
    collected_terms: list[str] = []
    text_lower = text_content.lower()

    # 1. Closed taxonomy & structured slot extraction
    topic, slots = extract_structured_slots(text_content)
    if topic in CANONICAL_TOPICS:
        collected_terms.append(topic.replace("_", " ").lower())
    for k, v in slots.items():
        collected_terms.append(f"{k} {v}")

    # 2. Bootstrapping teacher rules
    for rule in COMMERCIAL_ISSUE_RULES:
        matched = False
        for kw in rule["keywords"]:
            if re.search(kw, text_lower):
                matched = True
                break
        if matched:
            spotted.append({
                "issue": rule["issue"],
                "domain": rule["domain"],
                "governing_authorities": rule["governing_authorities"]
            })
            collected_terms.append(rule["commercial_terms"])

    if collected_terms:
        expanded_query = f"{text_content} {' '.join(collected_terms)}"
    else:
        expanded_query = text_content

    return expanded_query, spotted


class RetrievalError(RuntimeError):
    """Raised when contract or policy search fails."""


class EmbeddingCache:
    """Thread-safe LRU cache for embeddings keyed by model and sha256 text hash."""
    def __init__(self, maxsize: int = 10000):
        self.maxsize = maxsize
        self._cache: OrderedDict[str, list[float]] = OrderedDict()
        self._lock = threading.Lock()
        self.hits = 0
        self.misses = 0

    def _key(self, model: str, text: str) -> str:
        text_hash = hashlib.sha256(text.encode("utf-8")).hexdigest()
        return f"{model}:{text_hash}"

    def get(self, model: str, text: str) -> list[float] | None:
        key = self._key(model, text)
        with self._lock:
            if key in self._cache:
                self.hits += 1
                self._cache.move_to_end(key)
                return self._cache[key]
            self.misses += 1
            return None

    def set(self, model: str, text: str, vector: list[float]) -> None:
        key = self._key(model, text)
        with self._lock:
            self._cache[key] = vector
            self._cache.move_to_end(key)
            if len(self._cache) > self.maxsize:
                self._cache.popitem(last=False)

    def stats(self) -> dict[str, Any]:
        with self._lock:
            total = self.hits + self.misses
            hit_ratio = (self.hits / total) if total > 0 else 0.0
            return {
                "size": len(self._cache),
                "maxsize": self.maxsize,
                "hits": self.hits,
                "misses": self.misses,
                "hit_ratio": round(hit_ratio, 4)
            }

    def clear(self) -> None:
        with self._lock:
            self._cache.clear()
            self.hits = 0
            self.misses = 0


embedding_cache = EmbeddingCache(maxsize=10000)


def get_embeddings_batch(queries: list[str]) -> list[list[float]]:
    """Generate vector embeddings in batch via Ollama API with LRU cache."""
    if not queries:
        return []
    clean_queries = [q.strip() if q and q.strip() else " " for q in queries]

    results: list[list[float] | None] = [None] * len(clean_queries)
    miss_indices: list[int] = []
    miss_texts: list[str] = []

    for idx, q in enumerate(clean_queries):
        cached = embedding_cache.get(settings.OLLAMA_EMBED_MODEL, q)
        if cached is not None:
            results[idx] = cached
        else:
            miss_indices.append(idx)
            miss_texts.append(q)

    if not miss_texts:
        return [r for r in results if r is not None]

    payload = {
        "model": settings.OLLAMA_EMBED_MODEL,
        "input": miss_texts
    }
    fetched: list[list[float]] = []
    try:
        timeout = max(settings.EMBED_TIMEOUT, settings.EMBED_TIMEOUT * (len(miss_texts) / 8.0))
        with httpx.Client(timeout=timeout) as client:
            resp = client.post(f"{settings.OLLAMA_EMBED_HOST}/api/embed", json=payload)
            if resp.status_code == 404:
                # Fallback to single queries
                for mt in miss_texts:
                    s_resp = client.post(
                        f"{settings.OLLAMA_EMBED_HOST}/api/embeddings",
                        json={"model": settings.OLLAMA_EMBED_MODEL, "prompt": mt}
                    )
                    s_resp.raise_for_status()
                    fetched.append(s_resp.json().get("embedding", []))
            else:
                resp.raise_for_status()
                data = resp.json()
                fetched = data.get("embeddings", [])

        for idx, vec in zip(miss_indices, fetched):
            embedding_cache.set(settings.OLLAMA_EMBED_MODEL, clean_queries[idx], vec)
            results[idx] = vec

    except Exception as e:
        logger.warning(f"Ollama batch embedding generation unavailable ({e}). Using mock vectors for offline mode.")
        for idx in miss_indices:
            dummy_vec = [0.05] * settings.EMBEDDING_DIM
            results[idx] = dummy_vec

    return [r for r in results if r is not None]


def get_embedding(query: str) -> list[float]:
    """Generate vector embedding for single query."""
    res = get_embeddings_batch([query])
    return res[0] if res else [0.05] * settings.EMBEDDING_DIM


def retrieve_clauses(
    db: Session,
    query: str,
    limit: int = 5,
    offset: int = 0,
    organization: str | None = None,
    agreement_type: str | None = None,
    domain: str | None = None,
    deal_id: int | None = None,
    exclude_superseded: bool = True,
    topic: str | None = None,
    tag: str | None = None,
    tenant_id: str = "org_default"
) -> list[dict[str, Any]]:
    """
    Hybrid semantic (ANN) + lexical (FTS) retrieval across commercial contracts and policies.
    Applies Reciprocal Rank Fusion, hierarchical authority weighting, and explainability tracking.
    """
    if not query or not query.strip():
        return []

    expanded_query, spotted_issues = expand_commercial_query(query)
    is_sqlite = db.bind.dialect.name == "sqlite"

    query_vector = None
    try:
        query_vector = get_embedding(expanded_query)
    except Exception as e:
        logger.warning(f"Could not generate vector embedding for search ({e}), relying on lexical.")

    quoted_phrases = re.findall(r'"([^"]+)"', query)
    section_patterns = re.findall(
        r'(?:section|clause|art(?:icle)?|lease\s*§|§)\s*([\w\.\-]+(?:\([a-zA-Z\d]+\))*)',
        expanded_query,
        re.IGNORECASE
    )
    spotted_auths = [issue["governing_authorities"].lower() for issue in spotted_issues if issue.get("governing_authorities")]

    raw_candidates: dict[int, dict[str, Any]] = {}

    if not is_sqlite and query_vector is not None:
        try:
            vec_str = json.dumps(query_vector)
            sql = """
                WITH vector_ranks AS (
                    SELECT id,
                           (1.0 - (embedding <=> :query_vector::vector)) AS sim_score,
                           ROW_NUMBER() OVER (ORDER BY embedding <=> :query_vector::vector) as v_rank
                    FROM commercial_clauses_vectors
                    WHERE embedding IS NOT NULL
                      AND tenant_id = :tenant_id
                      AND (:organization IS NULL OR organization ILIKE :organization)
                      AND (:agreement_type IS NULL OR agreement_type ILIKE :agreement_type)
                      AND (:domain IS NULL OR domain ILIKE :domain)
                      AND (:topic IS NULL OR topic ILIKE :topic)
                      AND (:tag IS NULL OR tags ILIKE :tag)
                      AND (:exclude_superseded = FALSE OR (superseded = FALSE AND terminated = FALSE))
                    LIMIT 40
                ),
                fts_ranks AS (
                    SELECT id,
                           ts_rank_cd(
                               to_tsvector('english', coalesce(title, '') || ' ' || coalesce(section, '') || ' ' || coalesce(content, '')),
                               plainto_tsquery('english', :query)
                           ) as fts_score,
                           ROW_NUMBER() OVER (
                               ORDER BY ts_rank_cd(
                                   to_tsvector('english', coalesce(title, '') || ' ' || coalesce(section, '') || ' ' || coalesce(content, '')),
                                   plainto_tsquery('english', :query)
                               ) DESC
                           ) as f_rank
                    FROM commercial_clauses_vectors
                    WHERE tenant_id = :tenant_id
                      AND to_tsvector('english', coalesce(title, '') || ' ' || coalesce(section, '') || ' ' || coalesce(content, '')) @@ plainto_tsquery('english', :query)
                      AND (:organization IS NULL OR organization ILIKE :organization)
                      AND (:agreement_type IS NULL OR agreement_type ILIKE :agreement_type)
                      AND (:domain IS NULL OR domain ILIKE :domain)
                      AND (:topic IS NULL OR topic ILIKE :topic)
                      AND (:tag IS NULL OR tags ILIKE :tag)
                      AND (:exclude_superseded = FALSE OR (superseded = FALSE AND terminated = FALSE))
                    LIMIT 40
                )
                SELECT c.id, c.organization, c.counterparty, c.agreement_type, c.domain,
                       c.title, c.section, c.parent_section, c.hierarchy_level,
                       c.definitions_ref, c.exceptions_ref, c.authority_class,
                       c.effective_date, c.superseded, c.terminated, c.superseded_by,
                       c.source_url, c.content, c.structured_slots, c.topic, c.tags, c.summary,
                       COALESCE(vr.sim_score, 0.0) as vector_score,
                       COALESCE(fr.fts_score, 0.0) as fts_score,
                       COALESCE(1.0 / (60 + vr.v_rank), 0.0) + COALESCE(1.0 / (60 + fr.f_rank), 0.0) as rrf_score
                FROM commercial_clauses_vectors c
                LEFT JOIN vector_ranks vr ON c.id = vr.id
                LEFT JOIN fts_ranks fr ON c.id = fr.id
                WHERE vr.id IS NOT NULL OR fr.id IS NOT NULL;
            """
            params = {
                "query_vector": vec_str,
                "query": query,
                "tenant_id": tenant_id,
                "organization": organization,
                "agreement_type": agreement_type,
                "domain": domain,
                "topic": topic,
                "tag": f"%{tag}%" if tag else None,
                "exclude_superseded": exclude_superseded,
            }
            results = db.execute(text(sql), params).fetchall()
            for r in results:
                raw_tags = []
                if getattr(r, "tags", None):
                    try:
                        raw_tags = json.loads(r.tags) if isinstance(r.tags, str) else list(r.tags)
                    except Exception:
                        raw_tags = [t.strip() for t in str(r.tags).split(",") if t.strip()]

                raw_candidates[r.id] = {
                    "id": r.id,
                    "organization": r.organization,
                    "counterparty": r.counterparty,
                    "agreement_type": r.agreement_type,
                    "domain": r.domain,
                    "title": r.title,
                    "section": r.section,
                    "parent_section": r.parent_section,
                    "hierarchy_level": r.hierarchy_level,
                    "definitions_ref": r.definitions_ref,
                    "exceptions_ref": r.exceptions_ref,
                    "authority_class": r.authority_class,
                    "effective_date": r.effective_date,
                    "superseded": r.superseded,
                    "terminated": r.terminated,
                    "superseded_by": r.superseded_by,
                    "source_url": r.source_url,
                    "content": r.content,
                    "structured_slots": r.structured_slots,
                    "topic": getattr(r, "topic", None),
                    "tags": raw_tags,
                    "summary": getattr(r, "summary", None),
                    "vector_score": float(r.vector_score),
                    "lexical_score": float(r.fts_score),
                    "score": float(r.rrf_score),
                }
        except Exception as e:
            logger.warning(f"PostgreSQL hybrid query fallback to ORM search: {e}")
            raw_candidates.clear()

    if not raw_candidates:
        base_query = db.query(CommercialClauseVector).filter(CommercialClauseVector.tenant_id == tenant_id)
        if exclude_superseded:
            base_query = base_query.filter(
                CommercialClauseVector.superseded.is_(False),
                CommercialClauseVector.terminated.is_(False)
            )
        if organization:
            base_query = base_query.filter(CommercialClauseVector.organization.ilike(f"%{organization}%"))
        if agreement_type:
            base_query = base_query.filter(CommercialClauseVector.agreement_type.ilike(f"%{agreement_type}%"))
        if domain:
            base_query = base_query.filter(CommercialClauseVector.domain.ilike(f"%{domain}%"))
        if topic:
            base_query = base_query.filter(CommercialClauseVector.topic.ilike(f"%{topic}%"))
        if tag:
            base_query = base_query.filter(CommercialClauseVector.tags.ilike(f"%{tag}%"))

        all_clauses = base_query.all()
        query_words = set(re.findall(r'\w+', expanded_query.lower()))

        for c in all_clauses:
            text_to_search = f"{c.title or ''} {c.section or ''} {c.content or ''}".lower()
            clause_words = set(re.findall(r'\w+', text_to_search))

            overlap = len(query_words.intersection(clause_words))
            lex_score = overlap / (len(query_words) + 1e-5)

            vec_score = 0.0
            if query_vector is not None and c.embedding:
                try:
                    c_vec = c.embedding if isinstance(c.embedding, list) else json.loads(c.embedding)
                    dot = sum(a * b for a, b in zip(query_vector, c_vec))
                    norm_a = math.sqrt(sum(a * a for a in query_vector))
                    norm_b = math.sqrt(sum(b * b for b in c_vec))
                    if norm_a > 0 and norm_b > 0:
                        vec_score = max(0.0, dot / (norm_a * norm_b))
                except Exception:
                    vec_score = 0.0

            combined_score = 0.5 * lex_score + 0.5 * vec_score
            if combined_score > 0.01 or overlap > 0:
                raw_tags = []
                if c.tags:
                    try:
                        raw_tags = json.loads(c.tags) if isinstance(c.tags, str) else list(c.tags)
                    except Exception:
                        raw_tags = [t.strip() for t in str(c.tags).split(",") if t.strip()]

                raw_candidates[c.id] = {
                    "id": c.id,
                    "organization": c.organization,
                    "counterparty": c.counterparty,
                    "agreement_type": c.agreement_type,
                    "domain": c.domain,
                    "title": c.title,
                    "section": c.section,
                    "parent_section": c.parent_section,
                    "hierarchy_level": c.hierarchy_level,
                    "definitions_ref": c.definitions_ref,
                    "exceptions_ref": c.exceptions_ref,
                    "authority_class": c.authority_class,
                    "effective_date": c.effective_date,
                    "superseded": c.superseded,
                    "terminated": c.terminated,
                    "superseded_by": c.superseded_by,
                    "source_url": c.source_url,
                    "content": c.content,
                    "structured_slots": c.structured_slots,
                    "topic": c.topic,
                    "tags": raw_tags,
                    "summary": c.summary,
                    "vector_score": vec_score,
                    "lexical_score": lex_score,
                    "score": combined_score,
                }

    # 3. Apply authority class weighting, exact section boost, and explainability breakdown
    scored_list = []
    for cand in raw_candidates.values():
        score = cand["score"]
        auth_class = cand.get("authority_class", "governing_agreement")
        auth_mult = AUTHORITY_WEIGHTS.get(auth_class, 1.0)
        score *= auth_mult

        section_str = cand.get("section", "").lower()
        title_str = cand.get("title", "").lower()
        content_lower = cand.get("content", "").lower()

        boost = 1.0
        for pat in section_patterns:
            clean_pat = re.sub(r'[^\w\.]', '', pat.lower())
            if clean_pat and (clean_pat in section_str or clean_pat in title_str):
                boost *= 1.4

        for phrase in quoted_phrases:
            if phrase.lower() in content_lower:
                boost *= 1.25

        for sp_auth in spotted_auths:
            if sp_auth in section_str or sp_auth in title_str:
                boost *= 1.6
                break

        score *= boost
        cand["score"] = score
        cand["explanation"] = {
            "lexical_score": round(cand.get("lexical_score", 0.0), 3),
            "vector_score": round(cand.get("vector_score", 0.0), 3),
            "authority_class": auth_class,
            "authority_weight": round(auth_mult, 2),
            "spotted_boost": round(boost, 2),
            "final_score": round(score, 3),
            "controlling_status": "superseded" if cand.get("superseded") else "active",
            "structured_slots": cand.get("structured_slots") or {}
        }
        scored_list.append(cand)

    scored_list.sort(key=lambda x: x["score"], reverse=True)
    return scored_list[offset:offset + limit]


def verify_commercial_grounding(
    analysis_text: str,
    retrieved_clauses: list[dict[str, Any]],
    allow_refusal: bool = True
) -> tuple[bool, list[dict[str, Any]], str, dict[str, Any]]:
    """
    Verify commercial assertions and citations in generated text against retrieved clauses.
    Applies:
      1. Section citation presence check (detects INVENTED_CLAUSE)
      2. Superseded agreement check (detects SUPERSEDED_TERM)
      3. Structured slot matching: compares numbers, days, percentages (detects DIVERGENT_TERM)
      4. Text span overlap validation
    """
    if not analysis_text or not analysis_text.strip():
        return False, [], "Analysis text is empty.", {"pass_rate": 0.0}

    # Map known sections for fast retrieval
    known_sections: dict[str, dict[str, Any]] = {}
    for c in retrieved_clauses:
        sec = c.get("section")
        if sec:
            clean_sec = re.sub(r'^(?:Section|Clause|Article|Lease §|Exhibit [A-Z] \(SLA\) Section|Exhibit [A-Z] \(DPA\) Section|§)\s*', '', sec, flags=re.IGNORECASE).strip()
            known_sections[clean_sec.lower()] = c
            known_sections[sec.lower()] = c
            alpha_num_sec = re.sub(r'[^\w\.]', '', sec.lower())
            known_sections[alpha_num_sec] = c

    claim_records: list[dict[str, Any]] = []
    sentences = [s.strip() for s in re.split(r'(?<=[.!?])\s+', analysis_text) if s.strip()]

    total_claims = 0
    supported_claims = 0
    unsupported_claims = 0
    invented_clauses = 0
    divergent_terms = 0
    superseded_terms = 0

    citation_pattern = re.compile(
        r'((?:(?:Exhibit\s+[A-Za-z\d]+(?:\s*\([A-Za-z0-9]+\))?|Article\s+[IVXLCDM\d]+|Lease)\s*,?\s*)?(?:Section|Clause|§)\s*[\w\.\-]+(?:\([a-zA-Z\d]+\))*|Exhibit\s+[A-Za-z\d]+|Lease\s*§\s*[\w\.\-]+)',
        re.IGNORECASE
    )

    for sentence in sentences:
        matches = list(citation_pattern.finditer(sentence))
        if not matches:
            continue

        for m in matches:
            total_claims += 1
            cited_sec_raw = m.group(0)
            cited_sec_clean = cited_sec_raw.lower().strip()
            clean_token = re.sub(r'[^\w\.]', '', cited_sec_clean)
            stripped_sec = re.sub(r'^(?:section|clause|article|lease\s*§|§)\s*', '', cited_sec_clean).strip()

            matching_clause = (
                known_sections.get(cited_sec_clean)
                or known_sections.get(clean_token)
                or known_sections.get(stripped_sec)
                or next((c for k, c in known_sections.items() if clean_token in k or k in clean_token), None)
            )

            # 1. Check: Invented clause
            if not matching_clause:
                invented_clauses += 1
                unsupported_claims += 1
                claim_records.append({
                    "claim_id": f"claim_{total_claims}",
                    "sentence": sentence,
                    "cited_authority": cited_sec_raw,
                    "status": "invented_clause",
                    "failure_mode": "INVENTED_CLAUSE",
                    "details": f"Cited authority '{cited_sec_raw}' does not exist in the retrieved commercial corpus.",
                    "evidence_span": None
                })
                continue

            # 2. Check: Superseded term
            if matching_clause.get("superseded") or matching_clause.get("terminated"):
                superseded_terms += 1
                unsupported_claims += 1
                claim_records.append({
                    "claim_id": f"claim_{total_claims}",
                    "sentence": sentence,
                    "cited_authority": cited_sec_raw,
                    "status": "superseded_term",
                    "failure_mode": "SUPERSEDED_TERM",
                    "details": f"Authority '{cited_sec_raw}' is superseded / inoperative (superseded by: {matching_clause.get('superseded_by', 'controlling agreement')}).",
                    "evidence_span": matching_clause.get("content", "")[:180] + "..."
                })
                continue

            # 3. Check: Structured slot discrepancy (e.g. Net 45 vs Net 30, $2M vs $1M)
            _, sent_slots = extract_structured_slots(sentence)
            clause_slots = matching_clause.get("structured_slots") or {}
            if not clause_slots:
                _, clause_slots = extract_structured_slots(matching_clause.get("content", ""))

            slot_divergence = False
            divergence_reason = ""
            for skey in ("net_days", "uptime_pct", "late_interest_pct", "cap_period_months", "cap_amount", "notice_hours", "notice_days", "credit_pct"):
                if skey in sent_slots and skey in clause_slots:
                    val_sent = sent_slots[skey]
                    val_clause = clause_slots[skey]
                    if val_sent != val_clause:
                        slot_divergence = True
                        divergence_reason = f"Asserted slot '{skey}={val_sent}' diverges from contract authority '{skey}={val_clause}'."
                        break

            if slot_divergence:
                divergent_terms += 1
                unsupported_claims += 1
                claim_records.append({
                    "claim_id": f"claim_{total_claims}",
                    "sentence": sentence,
                    "cited_authority": cited_sec_raw,
                    "status": "divergent_term",
                    "failure_mode": "DIVERGENT_TERM",
                    "details": divergence_reason,
                    "evidence_span": matching_clause.get("content", "")[:180] + "..."
                })
                continue

            # 4. Check: Lexical / token span overlap
            content = matching_clause.get("content", "")
            sent_words = set(re.findall(r'\w{4,}', sentence.lower()))
            content_words = set(re.findall(r'\w{4,}', content.lower()))
            overlap = sent_words.intersection(content_words)

            if len(overlap) >= 2 or len(sent_words) <= 3:
                supported_claims += 1
                span_match = content[:200] + ("..." if len(content) > 200 else "")
                claim_records.append({
                    "claim_id": f"claim_{total_claims}",
                    "sentence": sentence,
                    "cited_authority": cited_sec_raw,
                    "status": "verified_grounded",
                    "failure_mode": None,
                    "details": f"Substantiated by {matching_clause.get('title', cited_sec_raw)}.",
                    "evidence_span": span_match
                })
            else:
                divergent_terms += 1
                unsupported_claims += 1
                claim_records.append({
                    "claim_id": f"claim_{total_claims}",
                    "sentence": sentence,
                    "cited_authority": cited_sec_raw,
                    "status": "divergent_term",
                    "failure_mode": "DIVERGENT_TERM",
                    "details": f"Clause '{cited_sec_raw}' exists, but text diverges significantly from the asserted terms.",
                    "evidence_span": content[:180] + "..."
                })

    if total_claims == 0:
        pass_rate = 100.0
        advisory_md = "> 🛡️ **Assertion Grounding Status**: General descriptive text without explicit section citations."
    else:
        pass_rate = round((supported_claims / total_claims) * 100.0, 1)
        if pass_rate < 100.0:
            advisory_md = (
                f"> ⚠️ **COMMERCIAL GROUNDING WARNING**: Only {supported_claims}/{total_claims} assertions ({pass_rate}%) "
                f"are verified against the governing contract graph. "
                f"{invented_clauses} invented clause(s), {divergent_terms} divergent term(s), and {superseded_terms} superseded term(s) detected."
            )
        else:
            advisory_md = (
                f"> 🛡️ **COMMERCIAL GROUNDING VERIFIED**: 100% of asserted terms ({total_claims}/{total_claims}) "
                f"are fully supported by active, controlling contractual authorities."
            )

    stats = {
        "total_claims": total_claims,
        "supported_claims": supported_claims,
        "unsupported_claims": unsupported_claims,
        "invented_clauses": invented_clauses,
        "divergent_terms": divergent_terms,
        "superseded_terms": superseded_terms,
        "pass_rate": pass_rate
    }
    is_grounded = (unsupported_claims == 0)
    return is_grounded, claim_records, advisory_md, stats


def generate_executive_brief(
    deal_title: str,
    context_facts: str,
    clauses: list[dict[str, Any]],
    counterparty: str | None = None,
    deal_type: str | None = None,
    deal_code: str | None = None,
    deal_id: int | None = None,
    db: Any = None,
    model: str | None = None,
    temperature: float = 0.1,
    tenant_id: str = "org_default",
) -> tuple[str, dict[str, Any], list[dict[str, Any]]]:
    """
    Generate an executive commercial brief grounded in retrieved authorities.
    Refuses drafting if:
      - No authorities exist (CANNOT_DRAFT_WITHOUT_AUTHORITIES)
      - All authorities are superseded (REFUSAL_ALL_AUTHORITIES_SUPERSEDED)
    Persists GroundingAudit report to database if db and deal_id are provided.
    """
    # 1. Guardrail Refusal: No Authorities
    if not clauses:
        refusal_msg = (
            "CANNOT_DRAFT_WITHOUT_AUTHORITIES: Insufficient governing contracts, amendments, or corporate policies "
            "found in the local commercial graph to substantiate this deal review. "
            "Please ingest the governing Master Agreement, SLA, or SOW before requesting executive synthesis."
        )
        stats = {
            "total_claims": 0,
            "supported_claims": 0,
            "unsupported_claims": 0,
            "invented_clauses": 0,
            "divergent_terms": 0,
            "superseded_terms": 0,
            "pass_rate": 0.0,
            "refusal_reason": "CANNOT_DRAFT_WITHOUT_AUTHORITIES"
        }
        return refusal_msg, stats, []

    # 2. Guardrail Refusal: All Authorities Superseded
    if all(c.get("superseded", False) or c.get("terminated", False) for c in clauses):
        refusal_msg = (
            "REFUSAL_ALL_AUTHORITIES_SUPERSEDED: All governing authorities retrieved for this commercial matter "
            "are superseded, terminated, or expired instruments. "
            "Executive briefs cannot be drafted against inoperative terms. Please ingest active controlling agreements."
        )
        stats = {
            "total_claims": 0,
            "supported_claims": 0,
            "unsupported_claims": 0,
            "invented_clauses": 0,
            "divergent_terms": 0,
            "superseded_terms": len(clauses),
            "pass_rate": 0.0,
            "refusal_reason": "REFUSAL_ALL_AUTHORITIES_SUPERSEDED"
        }
        return refusal_msg, stats, []

    # 3. Guardrail Refusal: Contract Conflicts Detected across Active Authorities
    topic_clauses: dict[str, list[dict[str, Any]]] = {}
    for c in clauses:
        if not c.get("superseded", False) and not c.get("terminated", False):
            t = c.get("topic") or "GENERAL_COMMERCIAL"
            if t != "GENERAL_COMMERCIAL":
                topic_clauses.setdefault(t, []).append(c)

    conflicting_topic = None
    diverging_details = None
    for t, t_cls in topic_clauses.items():
        if len(t_cls) >= 2:
            first_slots = t_cls[0].get("structured_slots") or {}
            for other_c in t_cls[1:]:
                other_slots = other_c.get("structured_slots") or {}
                for k in ("net_days", "late_interest_pct", "uptime_pct", "cap_period_months", "notice_hours"):
                    if k in first_slots and k in other_slots and first_slots[k] != other_slots[k]:
                        conflicting_topic = t
                        diverging_details = f"{k}: {first_slots[k]} in '{t_cls[0].get('title')}' vs {other_slots[k]} in '{other_c.get('title')}'"
                        break
                if conflicting_topic:
                    break
        if conflicting_topic:
            break

    if conflicting_topic:
        refusal_msg = (
            f"CANNOT_DRAFT_WITH_ACTIVE_CONFLICTS: Contract conflict detected on topic '{conflicting_topic}' "
            f"between operative agreements ({diverging_details}). "
            f"KruschBiz strictly refuses to synthesize an executive brief while live controlling terms diverge. "
            f"Please run 'resolve_controlling_clause' or execute an amendment to harmonize the conflicting terms."
        )
        stats = {
            "total_claims": 0,
            "supported_claims": 0,
            "unsupported_claims": 0,
            "invented_clauses": 0,
            "divergent_terms": 1,
            "superseded_terms": 0,
            "pass_rate": 0.0,
            "refusal_reason": "CANNOT_DRAFT_WITH_ACTIVE_CONFLICTS",
            "conflict_details": diverging_details
        }
        return refusal_msg, stats, []

    model_name = model or settings.OLLAMA_LLM_MODEL
    authorities_text = ""
    for idx, c in enumerate(clauses[:5], 1):
        authorities_text += (
            f"[{idx}] {c.get('agreement_type')} | {c.get('section', 'General')} ({c.get('title', '')}):\n"
            f"{c.get('content', '')}\n\n"
        )

    system_prompt = (
        "You are an executive commercial counsel and corporate deal strategist. "
        "Your task is to draft a rigorous, balanced Executive Commercial Memorandum. "
        "Strict Rule: Every factual obligation, cap, SLA metric, and penalty MUST be explicitly cited to one of the "
        "governing authorities provided below (e.g. 'Pursuant to Section 4.1...'). "
        "Never invent sections or obligations not present in the authorities."
    )

    user_prompt = f"""
TRANSACTION: {deal_title}
COUNTERPARTY: {counterparty or 'Counterparty'}
TYPE: {deal_type or 'Commercial Transaction'}
BACKGROUND / DEAL FACTS:
{context_facts}

GOVERNING AUTHORITIES:
{authorities_text}

Draft the Executive Commercial Memorandum with 4 sections:
I. KEY COMMERCIAL TERMS & TRANSACTION OVERVIEW
II. MATERIAL RISK EXPOSURE & CARVE-OUTS
III. OPERATIONAL, SLA & COMPLIANCE ALIGNMENT
IV. STRATEGIC RECOMMENDATIONS & REDLINE PRIORITIES
"""

    analysis_text = None
    try:
        with httpx.Client(timeout=settings.LLM_TIMEOUT) as client:
            resp = client.post(
                f"{settings.OLLAMA_BASE_URL}/api/generate",
                json={
                    "model": model_name,
                    "prompt": user_prompt,
                    "system": system_prompt,
                    "stream": False,
                    "options": {"temperature": temperature}
                }
            )
            if resp.status_code == 200:
                analysis_text = resp.json().get("response")
    except Exception as e:
        logger.warning(f"Ollama generation unavailable ({e}). Using deterministic executive template.")

    if not analysis_text:
        c0 = clauses[0]
        sec0 = c0.get("section", "Section 1.1")
        title0 = c0.get("title", "Governing Agreement")

        analysis_text = f"""# EXECUTIVE COMMERCIAL MEMORANDUM

## I. KEY COMMERCIAL TERMS & TRANSACTION OVERVIEW
The proposed transaction '{deal_title}' involves counterparty {counterparty or 'the designated vendor'} under {deal_type or 'a Master Services Agreement'}.
Pursuant to {sec0} ({title0}), the foundational commercial structure establishes binding obligations between the parties. Key milestones and baseline deliverables align with the provisions set forth in the governing documentation.

## II. MATERIAL RISK EXPOSURE & CARVE-OUTS
A critical review of the risk architecture indicates significant exposure requiring executive attention. Under {sec0}, liability limitations and indemnification thresholds govern the financial exposure. Carve-outs for gross negligence, willful misconduct, and breach of confidentiality must be strictly preserved to protect corporate interests against uncapped exposure.

## III. OPERATIONAL, SLA & COMPLIANCE ALIGNMENT
Operational parameters demand strict enforcement of service delivery benchmarks. In accordance with {sec0}, performance metrics, maintenance schedules, and audit verification windows require continuous monitoring. Any divergence between operational actuals and agreed terms triggers formal remedy mechanisms.

## IV. STRATEGIC RECOMMENDATIONS & REDLINE PRIORITIES
1. **Preserve Carve-Out Invariants**: Maintain uncapped exposure exceptions under {sec0}.
2. **Harmonize Invoicing Benchmarks**: Verify payment milestones and credit calculations prior to execution.
3. **Audit Execution**: Exercise scheduled verification rights to validate compliance with data security and SLA thresholds.
"""

    is_grounded, claims, advisory, stats = verify_commercial_grounding(analysis_text, clauses)

    if db is not None and deal_id is not None:
        try:
            report = CommercialGroundingReport(
                tenant_id=tenant_id,
                deal_id=deal_id,
                total_claims=stats.get("total_claims", 0),
                supported_claims=stats.get("supported_claims", 0),
                unsupported_claims=stats.get("unsupported_claims", 0),
                invented_clauses=stats.get("invented_clauses", 0),
                divergent_terms=stats.get("divergent_terms", 0),
                superseded_terms=stats.get("superseded_terms", 0),
                pass_rate=stats.get("pass_rate", 100.0),
                claims_json=json.dumps(claims),
                advisory_markdown=advisory
            )
            db.add(report)
            db.commit()
        except Exception as e:
            logger.warning(f"Failed to persist grounding report for deal {deal_id}: {e}")

    full_output = f"{analysis_text}\n\n{advisory}\n\n---\n*{COMMERCIAL_DISCLAIMER}*"
    return full_output, stats, claims


def retrieve_deal_evidence(
    db: Session,
    deal_id: int,
    text_query: str | None = None,
    tag: str | None = None,
    topic: str | None = None,
    limit: int = 10,
    doc_type: str | None = None,
    tenant_id: str = "org_default"
) -> list[dict[str, Any]]:
    """
    Search deal room exhibits, vendor proposals, redlines, and commercial attachments
    strictly within a single deal matter.
    Combines dense embeddings, lexical matching, canonical topic filtering, and commercial semantic tags.
    Guarantees strict tenant and deal boundary isolation.
    """
    query = db.query(DealEvidence).filter(
        DealEvidence.deal_id == deal_id,
        DealEvidence.tenant_id == tenant_id
    )

    if doc_type:
        query = query.filter(DealEvidence.doc_type == doc_type)
    if topic:
        query = query.filter(DealEvidence.topic.ilike(f"%{topic}%"))
    if tag:
        clean_tag = tag.lower().strip()
        query = query.filter(DealEvidence.tags.ilike(f"%{clean_tag}%"))

    rows = query.all()
    if not rows:
        return []

    def _format_record(r: DealEvidence, score_val: float = 1.0) -> dict[str, Any]:
        tags_list: list[str] = []
        if r.tags:
            try:
                tags_list = json.loads(r.tags) if isinstance(r.tags, str) else list(r.tags)
            except Exception:
                tags_list = [t.strip() for t in str(r.tags).split(",") if t.strip()]
        return {
            "id": r.id,
            "deal_id": r.deal_id,
            "tenant_id": r.tenant_id,
            "filename": r.filename,
            "doc_type": r.doc_type,
            "page_number": r.page_number,
            "section_locator": r.section_locator,
            "chunk_index": r.chunk_index,
            "content": r.content,
            "tags": tags_list,
            "summary": r.summary,
            "topic": r.topic,
            "similarity": round(float(score_val), 4),
            "created_at": r.created_at.isoformat() if r.created_at else None
        }

    if not text_query or not text_query.strip():
        return [_format_record(r, 1.0) for r in rows[:limit]]

    # Dense and lexical scoring
    q_vec = None
    try:
        q_vec = get_embedding(text_query)
    except Exception as e:
        logger.warning(f"Embedding error for deal evidence query: {e}")

    norm_q = math.sqrt(sum(a * a for a in q_vec)) if q_vec else 0.0
    q_tokens = set(re.findall(r'\b[a-zA-Z0-9\.\-]{3,}\b', text_query.lower()))

    scored_results = []
    for r in rows:
        cos_sim = 0.0
        if q_vec and r.embedding:
            try:
                emb = json.loads(r.embedding) if isinstance(r.embedding, str) else r.embedding
                dot = sum(a * b for a, b in zip(q_vec, emb))
                norm_e = math.sqrt(sum(b * b for b in emb))
                if norm_q > 0 and norm_e > 0:
                    cos_sim = dot / (norm_q * norm_e)
            except Exception:
                cos_sim = 0.0

        lex_score = 0.0
        tag_boost = 0.0
        if q_tokens:
            tags_str = r.tags or ""
            summary_str = r.summary or ""
            doc_text = f"{r.filename} {r.section_locator or ''} {summary_str} {tags_str} {r.content}".lower()
            matches = sum(1 for t in q_tokens if t in doc_text)
            lex_score = min(1.0, matches / max(1, len(q_tokens)))

            # Tag boost
            for t in q_tokens:
                if t in tags_str.lower():
                    tag_boost = max(tag_boost, 0.2)

        score = (0.6 * cos_sim) + (0.25 * lex_score) + (0.15 * tag_boost)
        scored_results.append((score, r))

    scored_results.sort(key=lambda x: x[0], reverse=True)
    return [_format_record(r, s) for s, r in scored_results[:limit]]
