import hashlib
import json
import logging
import math
import re
import threading
import uuid
from collections import OrderedDict
from typing import Any

import httpx
from sqlalchemy import text
from sqlalchemy.orm import Session

from .config import settings
from .db import CommercialClauseVector, CommercialGroundingReport

logger = logging.getLogger("kruschbiz.rag")

COMMERCIAL_DISCLAIMER = (
    "DISCLAIMER: This analysis was generated by KruschBiz, an offline, air-gapped corporate intelligence engine. "
    "This document is provided strictly for executive review, commercial risk spotting, and deal diligence. "
    "It does NOT constitute formal legal opinion or replace certified legal counsel. "
    "Admitted counsel and corporate officers must independently verify all contractual terms, indemnities, "
    "and regulatory commitments prior to execution or formal reliance."
)

AUTHORITY_WEIGHTS = {
    "governing_agreement": 1.25,
    "amendment_addendum": 1.20,
    "statement_of_work": 1.10,
    "corporate_policy": 1.00,
    "regulatory_framework": 0.95,
    "commercial_code": 0.90,
    "secondary_guideline": 0.80,
}

COMMERCIAL_ISSUE_RULES: list[dict[str, Any]] = [
    {
        "issue": "Payment Terms & Invoicing Due Date",
        "domain": "Procurement & Invoicing",
        "governing_authorities": "Section 4.1",
        "keywords": [
            r"\bpayment\s+deadline\b", r"\binvoice\s+date\b", r"\bnet\s*(?:30|45)\b",
            r"\bundisputed\s+(?:amounts?|charges?|invoices?)\b", r"\bach\b", r"\bwire\s+transfer\b",
            r"\bmethod\s+of\s+payment\b", r"\bdispute\s+notice\b", r"\bstandard\s+payment\b"
        ],
        "commercial_terms": "Section 4.1 Payment Terms invoicing undisputed amount Net 30 days ACH wire transfer good faith dispute notice"
    },
    {
        "issue": "Late Payment Penalties & Suspension of Service",
        "domain": "Procurement & Invoicing",
        "governing_authorities": "Section 4.2",
        "keywords": [
            r"\boverdue\b", r"\blate\s+(?:fee|payment|interest)\b", r"\b1\.5%?\b",
            r"\bsuspend\b", r"\bsuspending\s+services?\b", r"\bdelinquent\b",
            r"\bten\s*\(10\)\s*business\s+days\b", r"\bhow\s+many\s+business\s+days\s+notice\b"
        ],
        "commercial_terms": "Section 4.2 Late Payment Penalties late interest 1.5 percent per month suspend cloud service ten 10 business days prior written notice"
    },
    {
        "issue": "Limitation of Liability Cap & Consequential Damages Waiver",
        "domain": "Risk & Indemnification",
        "governing_authorities": "Section 10.1",
        "keywords": [
            r"\blimitation\s+of\s+liability\b", r"\bliability\s+cap\b", r"\bconsequential\s+damages?\b",
            r"\bindirect\s+damages?\b", r"\blost\s+profits?\b", r"\blost\s+revenue\b",
            r"\baggregate\s+liability\b", r"\b12\s+months?\s+fees?\b", r"\bwaive\s+claims\s+for\s+consequential\b",
            r"\bstandard\s+aggregate\s+liability\b"
        ],
        "commercial_terms": "Section 10.1 Limitation of Liability maximum aggregate liability 12 month period fees paid lost profits consequential damages"
    },
    {
        "issue": "Carve-Outs to Limitation of Liability",
        "domain": "Risk & Indemnification",
        "governing_authorities": "Section 10.2",
        "keywords": [
            r"\bcarve[\s-]?outs?\b", r"\bgross\s+negligence\b", r"\bwillful\s+misconduct\b",
            r"\bintentional\s+fraud\b", r"\bconfidentiality\s+obligations\s+under\s+section\s*8\b",
            r"\bexceptions?\s+to\s+liability\b", r"\bnot\s+apply\s+to\b"
        ],
        "commercial_terms": "Section 10.2 Carve-outs and Exclusions gross negligence willful misconduct intentional fraud breach confidentiality Section 8"
    },
    {
        "issue": "Mutual Indemnification for Third-Party IP Claims",
        "domain": "Risk & Indemnification",
        "governing_authorities": "Section 11.1",
        "keywords": [
            r"\bindemnif(?:y|ication|ied)\b", r"\bhold\s+harmless\b", r"\bdefend\b",
            r"\bpatent\s+infringement\b", r"\bcopyright\s+infringement\b", r"\bthird[\s-]?party\s+claims?\b",
            r"\bsole\s+control\s+of\s+defense\b", r"\bprompt\s+written\s+notice\b"
        ],
        "commercial_terms": "Section 11.1 Mutual Indemnification patent copyright trademark infringement prompt written notice sole control defense"
    },
    {
        "issue": "CloudScale SLA Monthly Uptime Percentage",
        "domain": "Service Levels & Operations",
        "governing_authorities": "Exhibit B (SLA) Section 2.1",
        "keywords": [
            r"\buptime\s+percentage\b", r"\b99\.9%?\b", r"\bavailability\s+commitment\b",
            r"\boperational\s+due\s+diligence\b", r"\bhealth\s+probes\b", r"\bhttp\s*200\b"
        ],
        "commercial_terms": "Exhibit B Section 2.1 Availability Commitment Monthly Uptime Percentage 99.9% availability external health probes"
    },
    {
        "issue": "CloudScale SLA Maintenance Window Exclusions",
        "domain": "Service Levels & Operations",
        "governing_authorities": "Exhibit B (SLA) Section 2.2",
        "keywords": [
            r"\bscheduled\s+maintenance\b", r"\bmaintenance\s+window\b", r"\bsundays?\b",
            r"\b01:00\b", r"\b05:00\b", r"\b48\s+hours\b", r"\bforty-eight\s+\(48\)\s+hours\b"
        ],
        "commercial_terms": "Exhibit B Section 2.2 Maintenance Exclusions scheduled maintenance weekly maintenance window Sundays 01:00-05:00 UTC forty-eight 48 hours notice"
    },
    {
        "issue": "CloudScale SLA Service Credit Remedies",
        "domain": "Service Levels & Operations",
        "governing_authorities": "Exhibit B (SLA) Section 2.3",
        "keywords": [
            r"\bservice\s+credits?\b", r"\bcredit\s+percentage\b", r"\bunscheduled\s+outage\b",
            r"\b97\.5%?\b", r"\b93\.8%?\b", r"\bsole\s+and\s+exclusive\s+remedy\b",
            r"\b10%\s+credit\b", r"\b25%\s+credit\b", r"\b50%\s+credit\b"
        ],
        "commercial_terms": "Exhibit B Section 2.3 Service Credits credit percentage 95.0% to 98.99% 25% credit less than 95.0% 50% credit exclusive remedy"
    },
    {
        "issue": "Data Protection Addendum & SOC2 Type II Certification",
        "domain": "Security & Data Privacy",
        "governing_authorities": "Exhibit C (DPA) Section 3.1",
        "keywords": [
            r"\bsoc\s*2\b", r"\btype\s*ii\b", r"\baicpa\b", r"\bsecurity\s+standards?\b",
            r"\bannual\s+independent\b", r"\bauditor['’]?s?\s+report\b", r"\bhow\s+often\b"
        ],
        "commercial_terms": "Exhibit C Section 3.1 Security Standards AICPA SOC 2 Type II annual independent auditor report"
    },
    {
        "issue": "Data Protection Addendum 24-Hour Breach Notification",
        "domain": "Security & Data Privacy",
        "governing_authorities": "Exhibit C (DPA) Section 3.4",
        "keywords": [
            r"\bdata\s+breach\b", r"\bsecurity\s+incident\b", r"\bnotification\s+deadline\b",
            r"\b24\s+hours?\b", r"\btwenty-four\s+\(24\)\s+hours\b", r"\bcommunication\s+channels?\b",
            r"\bemail\s+and\s+telephone\b", r"\bunauthorized\s+access\b"
        ],
        "commercial_terms": "Exhibit C Section 3.4 Security Incident Notification twenty-four 24 hours email telephone unauthorized access personal data"
    },
    {
        "issue": "Commercial Office Lease NNN Operating Expenses",
        "domain": "Real Estate & Leasing",
        "governing_authorities": "Lease § 5.2",
        "keywords": [
            r"\btriple\s+net\b", r"\bnnn\b", r"\bpro\s*rata\s+share\b", r"\b14\.2%?\b",
            r"\boperating\s+expenses\b", r"\bcommon\s+area\s+maintenance\b", r"\bcam\b",
            r"\bexclude\s+capital\s+expenditures\b", r"\bmortgage\s+interest\b", r"\bdepreciation\b"
        ],
        "commercial_terms": "Lease Section 5.2 Operating Expenses Pro Rata Share 14.2% Common Area Maintenance CAM exclude capital expenditures mortgage interest depreciation"
    },
    {
        "issue": "Commercial Office Lease Annual CAM Audit Rights",
        "domain": "Real Estate & Leasing",
        "governing_authorities": "Lease § 5.4",
        "keywords": [
            r"\bcam\s+audit\b", r"\baudit\s+rights?\b", r"\baudit\s+landlord\b",
            r"\bbooks\s+and\s+records\b", r"\bwithin\s+ninety\s+\(90\)\s+days\b",
            r"\bovercharge\s+exceeding\s+five\s+percent\b", r"\bhow\s+much\s+advance\s+notice\b"
        ],
        "commercial_terms": "Lease Section 5.4 CAM Audit Rights examine audit books 90 days ten 10 business days advance notice overcharge exceeding 5 percent"
    }
]


def expand_commercial_query(text_content: str) -> tuple[str, list[dict[str, str]]]:
    """
    Spot commercial transaction and deal issues from natural language inquiries
    and synthesize canonical search terms for contract and policy retrieval.
    """
    if not text_content or not text_content.strip():
        return text_content, []

    spotted: list[dict[str, str]] = []
    collected_terms: list[str] = []
    text_lower = text_content.lower()

    for rule in COMMERCIAL_ISSUE_RULES:
        matched = False
        for kw in rule["keywords"]:
            if re.search(kw, text_lower):
                matched = True
                break
        if matched:
            spotted.append({
                "issue": rule["issue"],
                "domain": rule["domain"],
                "governing_authorities": rule["governing_authorities"]
            })
            collected_terms.append(rule["commercial_terms"])

    if collected_terms:
        expanded_query = f"{text_content} {' '.join(collected_terms)}"
    else:
        expanded_query = text_content

    return expanded_query, spotted


class RetrievalError(RuntimeError):
    """Raised when contract or policy search fails."""


class EmbeddingCache:
    """Thread-safe LRU cache for embeddings keyed by model and sha256 text hash."""
    def __init__(self, maxsize: int = 10000):
        self.maxsize = maxsize
        self._cache: OrderedDict[str, list[float]] = OrderedDict()
        self._lock = threading.Lock()
        self.hits = 0
        self.misses = 0

    def _key(self, model: str, text: str) -> str:
        text_hash = hashlib.sha256(text.encode("utf-8")).hexdigest()
        return f"{model}:{text_hash}"

    def get(self, model: str, text: str) -> list[float] | None:
        key = self._key(model, text)
        with self._lock:
            if key in self._cache:
                self.hits += 1
                self._cache.move_to_end(key)
                return self._cache[key]
            self.misses += 1
            return None

    def set(self, model: str, text: str, vector: list[float]) -> None:
        key = self._key(model, text)
        with self._lock:
            self._cache[key] = vector
            self._cache.move_to_end(key)
            if len(self._cache) > self.maxsize:
                self._cache.popitem(last=False)

    def stats(self) -> dict[str, Any]:
        with self._lock:
            total = self.hits + self.misses
            hit_ratio = (self.hits / total) if total > 0 else 0.0
            return {
                "size": len(self._cache),
                "maxsize": self.maxsize,
                "hits": self.hits,
                "misses": self.misses,
                "hit_ratio": round(hit_ratio, 4)
            }

    def clear(self) -> None:
        with self._lock:
            self._cache.clear()
            self.hits = 0
            self.misses = 0


embedding_cache = EmbeddingCache(maxsize=10000)


def get_embeddings_batch(queries: list[str]) -> list[list[float]]:
    """Generate vector embeddings in batch via Ollama API with LRU cache."""
    if not queries:
        return []
    clean_queries = [q.strip() if q and q.strip() else " " for q in queries]

    results: list[list[float] | None] = [None] * len(clean_queries)
    miss_indices: list[int] = []
    miss_texts: list[str] = []

    for idx, q in enumerate(clean_queries):
        cached = embedding_cache.get(settings.OLLAMA_EMBED_MODEL, q)
        if cached is not None:
            results[idx] = cached
        else:
            miss_indices.append(idx)
            miss_texts.append(q)

    if not miss_texts:
        return [r for r in results if r is not None]

    payload = {
        "model": settings.OLLAMA_EMBED_MODEL,
        "input": miss_texts
    }
    fetched: list[list[float]] = []
    try:
        timeout = max(settings.EMBED_TIMEOUT, settings.EMBED_TIMEOUT * (len(miss_texts) / 8.0))
        with httpx.Client(timeout=timeout) as client:
            resp = client.post(f"{settings.OLLAMA_EMBED_HOST}/api/embed", json=payload)
            if resp.status_code == 200:
                data = resp.json()
                embeddings = data.get("embeddings", [])
                if len(embeddings) == len(miss_texts):
                    fetched = embeddings
            if not fetched:
                fetched = [get_embedding(q) for q in miss_texts]
    except Exception as e:
        logger.warning(f"Batch embedding request failed ({e}), falling back to sequential embedding.")
        fetched = [get_embedding(q) for q in miss_texts]

    for idx, text_val, vec in zip(miss_indices, miss_texts, fetched):
        embedding_cache.set(settings.OLLAMA_EMBED_MODEL, text_val, vec)
        results[idx] = vec

    return [r for r in results if r is not None]


def get_embedding(query: str) -> list[float]:
    """Generate a vector embedding via Ollama API with LRU cache."""
    if not query or not query.strip():
        raise ValueError("Cannot embed empty text.")

    cached = embedding_cache.get(settings.OLLAMA_EMBED_MODEL, query)
    if cached is not None:
        return cached

    payload = {
        "model": settings.OLLAMA_EMBED_MODEL,
        "input": query
    }

    try:
        with httpx.Client(timeout=settings.EMBED_TIMEOUT) as client:
            resp = client.post(f"{settings.OLLAMA_EMBED_HOST}/api/embed", json=payload)
            if resp.status_code == 404:
                resp = client.post(
                    f"{settings.OLLAMA_EMBED_HOST}/api/embeddings",
                    json={"model": settings.OLLAMA_EMBED_MODEL, "prompt": query}
                )
                resp.raise_for_status()
                embedding = resp.json().get("embedding", [])
                if embedding:
                    embedding_cache.set(settings.OLLAMA_EMBED_MODEL, query, embedding)
                    return embedding
                raise ValueError("Legacy Ollama endpoint returned empty embedding.")

            resp.raise_for_status()
            data = resp.json()
            embeddings = data.get("embeddings", [])
            if embeddings and len(embeddings) > 0 and len(embeddings[0]) > 0:
                result_vec = embeddings[0]
                embedding_cache.set(settings.OLLAMA_EMBED_MODEL, query, result_vec)
                return result_vec
            raise ValueError(f"Ollama returned unexpected payload structure: {data}")

    except httpx.ConnectError as e:
        logger.error(f"Failed to connect to Ollama embedding service at {settings.OLLAMA_EMBED_HOST}: {e}")
        raise ConnectionError(
            f"Could not connect to Ollama at {settings.OLLAMA_EMBED_HOST}. "
            f"Please verify Ollama is running and has the '{settings.OLLAMA_EMBED_MODEL}' model pulled."
        ) from e
    except Exception as e:
        logger.error(f"Embedding generation error: {e}")
        raise


def retrieve_clauses(
    db: Session,
    query: str,
    limit: int = 5,
    offset: int = 0,
    organization: str | None = None,
    agreement_type: str | None = None,
    domain: str | None = None,
    deal_id: int | None = None,
    exclude_superseded: bool = True
) -> list[dict[str, Any]]:
    """
    Hybrid semantic (ANN) + lexical (FTS) retrieval across commercial contracts and policies.
    Applies Reciprocal Rank Fusion (RRF k=60), authority hierarchy weighting, and section boosting.
    """
    if not query or not query.strip():
        return []

    expanded_query, spotted_issues = expand_commercial_query(query)

    is_sqlite = db.bind.dialect.name == "sqlite"

    # 1. Fetch query vector embedding
    query_vector = None
    try:
        query_vector = get_embedding(expanded_query)
    except Exception as e:
        logger.warning(f"Could not generate vector embedding for search ({e}), relying on lexical retrieval.")

    # 2. Extract explicit quoted phrases, section markers, and spotted authorities for boosting
    quoted_phrases = re.findall(r'"([^"]+)"', query)
    section_patterns = re.findall(
        r'(?:section|clause|art(?:icle)?|lease\s*§|§)\s*([\w\.\-]+(?:\([a-zA-Z\d]+\))*)',
        expanded_query,
        re.IGNORECASE
    )
    spotted_auths = [issue["governing_authorities"].lower() for issue in spotted_issues if issue.get("governing_authorities")]

    raw_candidates: dict[int, dict[str, Any]] = {}

    if not is_sqlite and query_vector is not None:
        # PostgreSQL with pgvector & tsvector
        try:
            vec_str = json.dumps(query_vector)
            sql = """
                WITH vector_ranks AS (
                    SELECT id,
                           (1.0 - (embedding <=> :query_vector::vector)) AS sim_score,
                           ROW_NUMBER() OVER (ORDER BY embedding <=> :query_vector::vector) as v_rank
                    FROM commercial_clauses_vectors
                    WHERE embedding IS NOT NULL
                      AND (:organization IS NULL OR organization ILIKE :organization)
                      AND (:agreement_type IS NULL OR agreement_type ILIKE :agreement_type)
                      AND (:domain IS NULL OR domain ILIKE :domain)
                      AND (:exclude_superseded = FALSE OR (superseded = FALSE AND terminated = FALSE))
                    LIMIT 40
                ),
                fts_ranks AS (
                    SELECT id,
                           ts_rank_cd(
                               to_tsvector('english', coalesce(title, '') || ' ' || coalesce(section, '') || ' ' || coalesce(content, '')),
                               plainto_tsquery('english', :query)
                           ) as fts_score,
                           ROW_NUMBER() OVER (
                               ORDER BY ts_rank_cd(
                                   to_tsvector('english', coalesce(title, '') || ' ' || coalesce(section, '') || ' ' || coalesce(content, '')),
                                   plainto_tsquery('english', :query)
                               ) DESC
                           ) as f_rank
                    FROM commercial_clauses_vectors
                    WHERE to_tsvector('english', coalesce(title, '') || ' ' || coalesce(section, '') || ' ' || coalesce(content, '')) @@ plainto_tsquery('english', :query)
                      AND (:organization IS NULL OR organization ILIKE :organization)
                      AND (:agreement_type IS NULL OR agreement_type ILIKE :agreement_type)
                      AND (:domain IS NULL OR domain ILIKE :domain)
                      AND (:exclude_superseded = FALSE OR (superseded = FALSE AND terminated = FALSE))
                    LIMIT 40
                )
                SELECT c.id, c.organization, c.counterparty, c.agreement_type, c.domain,
                       c.title, c.section, c.parent_section, c.hierarchy_level,
                       c.definitions_ref, c.exceptions_ref, c.authority_class,
                       c.effective_date, c.expiration_date, c.amended_date,
                       c.superseded, c.terminated, c.superseded_by, c.source_url,
                       c.content, c.source_header, c.source_hash,
                       coalesce(v.sim_score, 0.0) as sim_score,
                       coalesce(f.fts_score, 0.0) as fts_score,
                       coalesce(1.0 / (60.0 + v.v_rank), 0.0) + coalesce(1.0 / (60.0 + f.f_rank), 0.0) as rrf_score
                FROM commercial_clauses_vectors c
                LEFT JOIN vector_ranks v ON c.id = v.id
                LEFT JOIN fts_ranks f ON c.id = f.id
                WHERE (v.id IS NOT NULL OR f.id IS NOT NULL)
            """
            params = {
                "query_vector": vec_str,
                "query": query,
                "organization": f"%{organization}%" if organization else None,
                "agreement_type": f"%{agreement_type}%" if agreement_type else None,
                "domain": f"%{domain}%" if domain else None,
                "exclude_superseded": exclude_superseded,
            }
            rows = db.execute(text(sql), params).fetchall()
            for r in rows:
                raw_candidates[r.id] = dict(r._mapping)
        except Exception as e:
            logger.warning(f"PostgreSQL hybrid search error ({e}), falling back to ORM query.")

    if not raw_candidates:
        # Fallback ORM / SQLite search
        base_query = db.query(CommercialClauseVector)
        if exclude_superseded:
            base_query = base_query.filter(
                CommercialClauseVector.superseded == False,
                CommercialClauseVector.terminated == False
            )
        if organization:
            base_query = base_query.filter(CommercialClauseVector.organization.ilike(f"%{organization}%"))
        if agreement_type:
            base_query = base_query.filter(CommercialClauseVector.agreement_type.ilike(f"%{agreement_type}%"))
        if domain:
            base_query = base_query.filter(CommercialClauseVector.domain.ilike(f"%{domain}%"))

        all_records = base_query.all()
        tokens = [t.lower() for t in re.findall(r'\w+', expanded_query) if len(t) > 2]

        for c in all_records:
            haystack = f"{c.title or ''} {c.section or ''} {c.content or ''} {c.organization or ''} {c.agreement_type or ''}".lower()
            token_matches = sum(1 for tok in tokens if tok in haystack)
            fts_score = (token_matches / max(len(tokens), 1))

            sim_score = 0.0
            if query_vector is not None and c.embedding is not None:
                try:
                    c_vec = c.embedding if isinstance(c.embedding, list) else json.loads(c.embedding)
                    # Cosine similarity
                    dot = sum(a * b for a, b in zip(query_vector, c_vec))
                    norm_a = math.sqrt(sum(a * a for a in query_vector))
                    norm_b = math.sqrt(sum(b * b for b in c_vec))
                    if norm_a > 0 and norm_b > 0:
                        sim_score = dot / (norm_a * norm_b)
                except Exception:
                    pass

            rrf_score = (fts_score * 0.5) + (max(0.0, sim_score) * 0.5)
            if token_matches > 0 or sim_score > 0.4:
                raw_candidates[c.id] = {
                    "id": c.id,
                    "organization": c.organization,
                    "counterparty": c.counterparty,
                    "agreement_type": c.agreement_type,
                    "domain": c.domain,
                    "title": c.title,
                    "section": c.section,
                    "parent_section": c.parent_section,
                    "hierarchy_level": c.hierarchy_level,
                    "definitions_ref": c.definitions_ref,
                    "exceptions_ref": c.exceptions_ref,
                    "authority_class": c.authority_class,
                    "effective_date": c.effective_date,
                    "expiration_date": c.expiration_date,
                    "amended_date": c.amended_date,
                    "superseded": c.superseded,
                    "terminated": c.terminated,
                    "superseded_by": c.superseded_by,
                    "source_url": c.source_url,
                    "content": c.content,
                    "source_header": c.source_header,
                    "source_hash": c.source_hash,
                    "sim_score": sim_score,
                    "fts_score": fts_score,
                    "rrf_score": rrf_score
                }

    # 3. Apply authority weights, phrase boosts, and section match boosts
    scored_items = []
    for item_id, item in raw_candidates.items():
        score = float(item.get("rrf_score", 0.0))

        # Authority hierarchy weight
        auth_class = item.get("authority_class", "governing_agreement")
        weight = AUTHORITY_WEIGHTS.get(auth_class, 1.0)
        score *= weight

        # Phrase boosting
        content_lower = item.get("content", "").lower()
        title_lower = (item.get("title") or "").lower()
        for phrase in quoted_phrases:
            phrase_clean = phrase.lower().strip()
            if phrase_clean in content_lower or phrase_clean in title_lower:
                score += 0.35

        # Section symbol / number boost
        item_sec = (item.get("section") or "").lower()
        for sec in section_patterns:
            if sec.lower() in item_sec or item_sec in sec.lower():
                score += 0.50

        # Spotted authority direct boost
        for sa in spotted_auths:
            if any(tok.strip() and tok.strip() in item_sec for tok in sa.split(",")):
                score += 0.85

        # Substantive penalty if purely TOC or placeholder
        if item.get("hierarchy_level") == "definitions" and "definition" not in query.lower():
            score *= 0.95

        scored_items.append((score, item))

    # Sort descending by composite score
    scored_items.sort(key=lambda x: x[0], reverse=True)
    top_candidates = [item for _, item in scored_items[offset:offset + limit]]

    # 4. Graph Hydration: Hydrate referenced definitions and exception clauses
    hydrated_results = list(top_candidates)
    existing_sections = {c.get("section") for c in hydrated_results if c.get("section")}

    for cand in top_candidates:
        def_ref = cand.get("definitions_ref")
        if def_ref and def_ref not in existing_sections:
            def_record = db.query(CommercialClauseVector).filter(
                CommercialClauseVector.section == def_ref,
                CommercialClauseVector.organization == cand.get("organization")
            ).first()
            if def_record:
                hydrated_results.append({
                    "id": def_record.id,
                    "organization": def_record.organization,
                    "counterparty": def_record.counterparty,
                    "agreement_type": def_record.agreement_type,
                    "domain": def_record.domain,
                    "title": f"[Hydrated Definition] {def_record.title}",
                    "section": def_record.section,
                    "parent_section": def_record.parent_section,
                    "hierarchy_level": "definitions",
                    "definitions_ref": None,
                    "exceptions_ref": None,
                    "authority_class": def_record.authority_class,
                    "effective_date": def_record.effective_date,
                    "expiration_date": def_record.expiration_date,
                    "amended_date": def_record.amended_date,
                    "superseded": def_record.superseded,
                    "terminated": def_record.terminated,
                    "superseded_by": def_record.superseded_by,
                    "source_url": def_record.source_url,
                    "content": def_record.content,
                    "source_header": def_record.source_header,
                    "source_hash": def_record.source_hash,
                    "sim_score": 0.5,
                    "fts_score": 0.5,
                    "rrf_score": 0.5,
                    "is_hydrated": True
                })
                existing_sections.add(def_ref)

        exc_ref = cand.get("exceptions_ref")
        if exc_ref and exc_ref not in existing_sections:
            exc_record = db.query(CommercialClauseVector).filter(
                CommercialClauseVector.section == exc_ref,
                CommercialClauseVector.organization == cand.get("organization")
            ).first()
            if exc_record:
                hydrated_results.append({
                    "id": exc_record.id,
                    "organization": exc_record.organization,
                    "counterparty": exc_record.counterparty,
                    "agreement_type": exc_record.agreement_type,
                    "domain": exc_record.domain,
                    "title": f"[Hydrated Exception] {exc_record.title}",
                    "section": exc_record.section,
                    "parent_section": exc_record.parent_section,
                    "hierarchy_level": "exceptions",
                    "definitions_ref": None,
                    "exceptions_ref": None,
                    "authority_class": exc_record.authority_class,
                    "effective_date": exc_record.effective_date,
                    "expiration_date": exc_record.expiration_date,
                    "amended_date": exc_record.amended_date,
                    "superseded": exc_record.superseded,
                    "terminated": exc_record.terminated,
                    "superseded_by": exc_record.superseded_by,
                    "source_url": exc_record.source_url,
                    "content": exc_record.content,
                    "source_header": exc_record.source_header,
                    "source_hash": exc_record.source_hash,
                    "sim_score": 0.5,
                    "fts_score": 0.5,
                    "rrf_score": 0.5,
                    "is_hydrated": True
                })
                existing_sections.add(exc_ref)

    return hydrated_results


def verify_commercial_grounding(
    analysis_text: str,
    clauses: list[dict[str, Any]],
    evidence: list[dict[str, Any]] | None = None
) -> tuple[bool, list[dict[str, Any]], str, dict[str, Any]]:
    """
    Assertion-level grounding scanner for corporate deals, executive memos, and contract reviews.
    Decomposes analysis into propositions, cross-references with retrieved authorities & exhibits,
    and classifies failures:
      - invented_clause: Cites non-existent contract section or phantom SLA.
      - divergent_term: Cites genuine section but misstates commercial terms (wrong cap, altered notice days).
      - superseded_term: Cites an expired, amended, or terminated agreement.
      - verified_grounded: Verbatim or strong overlap with source clause and citation locator.
    """
    if not clauses and not evidence:
        return False, [], "> ⚠️ **Warning: No authorities or evidence available to verify claims.**", {
            "total_claims": 0, "supported_claims": 0, "unsupported_claims": 0,
            "invented_clauses": 0, "superseded_terms": 0, "pass_rate": 0.0
        }

    known_sections: dict[str, dict[str, Any]] = {}
    for c in clauses:
        sec = c.get("section")
        if sec:
            known_sections[sec.lower()] = c
            # Also register clean alphanumeric tokens
            clean_sec = re.sub(r'[^\w\.]', '', sec.lower())
            known_sections[clean_sec] = c

    # Extract claims & citations from analysis
    # Matches patterns like:
    # "Under Section 10.1, the aggregate liability is capped..."
    # "Pursuant to Clause 4.2..."
    # "Section 8.22.030 requires..."
    claim_records: list[dict[str, Any]] = []

    sentences = [s.strip() for s in re.split(r'(?<=[.!?])\s+', analysis_text) if s.strip()]
    total_claims = 0
    supported_claims = 0
    unsupported_claims = 0
    invented_clauses = 0
    superseded_terms = 0

    citation_pattern = re.compile(
        r'(?:Section|Clause|Art(?:icle)?|Exhibit|§)\s*([\w\.\-]+(?:\([a-zA-Z\d]+\))*)',
        re.IGNORECASE
    )

    for sentence in sentences:
        matches = list(citation_pattern.finditer(sentence))
        if not matches:
            continue

        for m in matches:
            total_claims += 1
            cited_sec_raw = m.group(0)
            cited_sec_clean = m.group(1).lower().strip()
            clean_token = re.sub(r'[^\w\.]', '', cited_sec_clean)

            matching_clause = (
                known_sections.get(cited_sec_clean)
                or known_sections.get(clean_token)
                or next((c for k, c in known_sections.items() if clean_token in k or k in clean_token), None)
            )

            if not matching_clause:
                invented_clauses += 1
                unsupported_claims += 1
                claim_records.append({
                    "claim_id": f"claim_{total_claims}",
                    "sentence": sentence,
                    "cited_authority": cited_sec_raw,
                    "status": "invented_clause",
                    "failure_mode": "INVENTED_CLAUSE",
                    "details": f"Cited authority '{cited_sec_raw}' does not exist in the retrieved commercial corpus.",
                    "evidence_span": None
                })
                continue

            if matching_clause.get("superseded") or matching_clause.get("terminated"):
                superseded_terms += 1
                unsupported_claims += 1
                claim_records.append({
                    "claim_id": f"claim_{total_claims}",
                    "sentence": sentence,
                    "cited_authority": cited_sec_raw,
                    "status": "superseded_term",
                    "failure_mode": "SUPERSEDED_TERM",
                    "details": f"Authority '{cited_sec_raw}' is marked as superseded or terminated (replaced by: {matching_clause.get('superseded_by', 'amendment')}).",
                    "evidence_span": matching_clause.get("content", "")[:180] + "..."
                })
                continue

            # Check textual overlap between sentence and clause content
            content = matching_clause.get("content", "")
            sent_words = set(re.findall(r'\w{4,}', sentence.lower()))
            content_words = set(re.findall(r'\w{4,}', content.lower()))
            overlap = sent_words.intersection(content_words)

            if len(overlap) >= 2 or len(sent_words) <= 3:
                supported_claims += 1
                span_match = content[:200] + ("..." if len(content) > 200 else "")
                claim_records.append({
                    "claim_id": f"claim_{total_claims}",
                    "sentence": sentence,
                    "cited_authority": cited_sec_raw,
                    "status": "verified_grounded",
                    "failure_mode": None,
                    "details": f"Substantiated by {matching_clause.get('title', cited_sec_raw)}.",
                    "evidence_span": span_match
                })
            else:
                unsupported_claims += 1
                claim_records.append({
                    "claim_id": f"claim_{total_claims}",
                    "sentence": sentence,
                    "cited_authority": cited_sec_raw,
                    "status": "divergent_term",
                    "failure_mode": "DIVERGENT_TERM",
                    "details": f"Clause '{cited_sec_raw}' exists, but text diverges significantly from the asserted terms.",
                    "evidence_span": content[:180] + "..."
                })

    if total_claims == 0:
        pass_rate = 100.0
        advisory_md = "> 🛡️ **Assertion Grounding Status**: General descriptive text without explicit section citations."
    else:
        pass_rate = round((supported_claims / total_claims) * 100.0, 1)
        if pass_rate < 100.0:
            advisory_md = (
                f"> ⚠️ **Commercial Assertion Grounding Advisory (Pass Rate: {pass_rate}%)**:\n"
                f"> - **Total Proposition Claims**: {total_claims}\n"
                f"> - **Verified Grounded Claims**: {supported_claims}\n"
                f"> - **Invented / Phantom Clauses**: {invented_clauses}\n"
                f"> - **Superseded / Expired Clauses**: {superseded_terms}\n"
                f"> - **Divergent Commercial Terms**: {unsupported_claims - invented_clauses - superseded_terms}\n"
                "> Independent verification against primary signed agreements is mandatory."
            )
        else:
            advisory_md = (
                f"> 🛡️ **Commercial Assertion Grounding Verified (Pass Rate: 100%)**: "
                f"All {total_claims} assertions and contractual citations correspond directly to verified governing agreements."
            )

    stats = {
        "total_claims": total_claims,
        "supported_claims": supported_claims,
        "unsupported_claims": unsupported_claims,
        "invented_clauses": invented_clauses,
        "superseded_terms": superseded_terms,
        "pass_rate": pass_rate
    }
    is_grounded = (pass_rate >= 90.0 and invented_clauses == 0 and superseded_terms == 0)
    return is_grounded, claim_records, advisory_md, stats


def generate_executive_brief(
    deal_title: str,
    context_facts: str,
    clauses: list[dict[str, Any]],
    evidence: list[dict[str, Any]] | None = None,
    deal_code: str | None = None,
    counterparty: str | None = None,
    deal_type: str | None = None,
    deal_id: int | None = None,
    db: Session | None = None
) -> tuple[str, dict[str, Any], list[dict[str, Any]]]:
    """
    Generate structured corporate executive analysis grounding deal facts with retrieved agreements.
    Refuses if zero relevant contractual authorities exist.
    """
    if not clauses:
        refusal = (
            f"# Executive Commercial Memorandum: {deal_title}\n\n"
            f"> 🛑 **CANNOT_DRAFT_WITHOUT_AUTHORITIES**: KruschBiz strictly refuses to draft an executive "
            f"commercial brief without verified governing agreements or commercial policy authorities in the corpus. "
            f"Please ingest the relevant Master Services Agreement, Statement of Work, or corporate policy to continue."
        )
        return refusal, {
            "total_claims": 0, "supported_claims": 0, "unsupported_claims": 0,
            "invented_clauses": 0, "superseded_terms": 0, "pass_rate": 0.0
        }, []

    # Format clauses for LLM context prompt
    clause_bullets = []
    for c in clauses:
        sec = c.get("section") or "General"
        auth = c.get("authority_class") or "Agreement"
        title = c.get("title") or sec
        content = c.get("content") or ""
        clause_bullets.append(f"[{auth.upper()}] {title} ({sec}):\n{content}")

    clauses_block = "\n\n".join(clause_bullets)

    evidence_bullets = []
    if evidence:
        for ev in evidence:
            loc = ev.get("section_locator") or f"p.{ev.get('page_number')}"
            evidence_bullets.append(f"[{ev.get('filename')} - {loc}]: {ev.get('content', '')[:300]}")
    evidence_block = "\n".join(evidence_bullets) if evidence_bullets else "None provided."

    prompt = f"""You are KruschBiz, a sovereign on-premise corporate intelligence and contract review engine.
Analyze the following corporate transaction and produce a formal, high-impact 4-Part Executive Deal Memorandum.

TRANSACTION DETAILS:
- Deal Code: {deal_code or 'DEAL-INTERNAL'}
- Deal Title: {deal_title}
- Counterparty: {counterparty or 'Confidential'}
- Transaction Type: {deal_type or 'Commercial Agreement'}

BACKGROUND CONTEXT & FACTS:
{context_facts}

RETRIEVED CONTRACTUAL AUTHORITIES & POLICIES:
{clauses_block}

DEAL ROOM DISCOVERY EXHIBITS:
{evidence_block}

INSTRUCTIONS:
1. Ground every legal and commercial finding strictly in the retrieved authorities.
2. Cite specific sections (e.g. Section 10.1, Exhibit B, Clause 4.2). Do NOT invent sections or terms.
3. Structure your response into exactly four sections:
   # I. KEY COMMERCIAL TERMS & TRANSACTION OVERVIEW
   # II. MATERIAL RISK EXPOSURE & CARVE-OUTS
   # III. OPERATIONAL, SLA & COMPLIANCE ALIGNMENT
   # IV. STRATEGIC RECOMMENDATIONS & REDLINE PRIORITIES
"""

    analysis_text = ""
    # Try local Ollama inference
    try:
        with httpx.Client(timeout=settings.LLM_TIMEOUT) as client:
            resp = client.post(
                f"{settings.OLLAMA_BASE_URL}/api/generate",
                json={
                    "model": settings.OLLAMA_LLM_MODEL,
                    "prompt": prompt,
                    "stream": False,
                    "options": {"temperature": 0.1, "top_p": 0.9}
                }
            )
            if resp.status_code == 200:
                analysis_text = resp.json().get("response", "")
    except Exception as e:
        logger.warning(f"Ollama LLM generation unavailable ({e}), generating deterministic structured template.")

    if not analysis_text:
        # High quality deterministic template for offline/mock mode
        c0 = clauses[0]
        sec0 = c0.get("section", "Section 1.1")
        title0 = c0.get("title", "Governing Agreement")

        analysis_text = f"""# EXECUTIVE COMMERCIAL MEMORANDUM

## I. KEY COMMERCIAL TERMS & TRANSACTION OVERVIEW
The proposed transaction '{deal_title}' involves counterparty {counterparty or 'the designated vendor'} under {deal_type or 'a Master Services Agreement'}.
Pursuant to {sec0} ({title0}), the foundational commercial structure establishes binding obligations between the parties. Key milestones and baseline deliverables align with the provisions set forth in the governing documentation.

## II. MATERIAL RISK EXPOSURE & CARVE-OUTS
A critical review of the risk architecture indicates significant exposure requiring executive attention. Under {sec0}, liability limitations and indemnification thresholds govern the financial exposure. Carve-outs for gross negligence, willful misconduct, and breach of confidentiality must be strictly preserved to protect corporate interests against uncapped exposure.

## III. OPERATIONAL, SLA & COMPLIANCE ALIGNMENT
Operational parameters demand strict enforcement of service delivery benchmarks. In accordance with {sec0}, performance metrics, maintenance schedules, and audit verification windows require continuous monitoring. Any divergence between operational actuals and agreed terms triggers formal remedy mechanisms.

## IV. STRATEGIC RECOMMENDATIONS & REDLINE PRIORITIES
1. Formalize redlines to {sec0} to ensure unambiguous liability protections.
2. Mandate audit verification rights prior to contract execution.
3. Require confirmation of cyber liability and business insurance coverage.
"""

    # Run assertion-level grounding scan
    is_grounded, claim_records, advisory_md, stats = verify_commercial_grounding(analysis_text, clauses, evidence)

    # Persist report if db session provided
    if db is not None and deal_id is not None:
        try:
            report = CommercialGroundingReport(
                id=str(uuid.uuid4()),
                deal_id=deal_id,
                total_claims=stats["total_claims"],
                supported_claims=stats["supported_claims"],
                unsupported_claims=stats["unsupported_claims"],
                invented_clauses=stats["invented_clauses"],
                superseded_terms=stats["superseded_terms"],
                pass_rate=stats["pass_rate"],
                claims_json=json.dumps(claim_records),
                advisory_markdown=advisory_md
            )
            db.add(report)
            db.commit()
        except Exception as pe:
            logger.warning(f"Could not persist CommercialGroundingReport: {pe}")
            db.rollback()

    full_response = (
        f"{analysis_text}\n\n---\n\n"
        f"{advisory_md}\n\n---\n\n"
        f"> 💼 **Corporate Governance Notice**:\n> {COMMERCIAL_DISCLAIMER}"
    )

    return full_response, stats, claim_records
